Repository redis/jedis, pull requests merged in 2019-03, with the labels that each got.

#1957 Backport of gh-1910 to fix race condition
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/test/java/redis/clients/jedis/tests/JedisSentinelPoolTest.java
Labels: READY TO MERGE

#1880 Add Redis Streams
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/StreamEntry.java
  src/main/java/redis/clients/jedis/StreamEntryID.java
  src/main/java/redis/clients/jedis/StreamPendingEntry.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommands.java
  src/main/java/redis/clients/jedis/commands/RedisPipeline.java
  src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
Labels: READY TO MERGE

#1832 Update commons-pool2 to version 2.6.1
  pom.xml
Labels: READY TO MERGE

#1934 Adds MEMORY DOCTOR command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: DISCUSSION NEEDED, READY TO MERGE

#1954 Create Unflushed getObjectMultiBulkReply variant in Connection
  src/main/java/redis/clients/jedis/BinaryJedisPubSub.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/JedisPubSub.java
Labels: READY TO MERGE

#1923 Throw an exception when trying to read from a broken connection
  src/main/java/redis/clients/jedis/Connection.java
  src/test/java/redis/clients/jedis/tests/ConnectionTest.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#1939 Reset shardjedis datasource
  src/main/java/redis/clients/jedis/ShardedJedis.java
Labels: WAIT FOR MORE REVIEWS

#1896 Add SSL support to JedisCluster
  Makefile
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java
  src/main/java/redis/clients/jedis/JedisClusterHostAndPortMap.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisSlotBasedConnectionHandler.java
  src/test/java/redis/clients/jedis/tests/SSLJedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisTest.java
Labels: WAIT FOR MORE REVIEWS
