Repository redis/jedis, pull requests merged in 2020-12, with the labels that each got.

#2288 Some code cleanup
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/HostAndPort.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisClusterCommand.java
  src/main/java/redis/clients/jedis/exceptions/JedisRedirectionException.java
  src/main/java/redis/clients/jedis/util/Hashing.java
  src/test/java/redis/clients/jedis/tests/JedisSentinelPoolTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
Labels: READY TO MERGE

#2279 add support for MEMORY USAGE
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#2204 Add hincrByFloat in JedisCluster
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/test/java/redis/clients/jedis/tests/commands/ClusterBinaryValuesCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ClusterJedisCommandsTestBase.java
  src/test/java/redis/clients/jedis/tests/commands/ClusterScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ClusterValuesCommandsTest.java
Labels: READY TO MERGE

#2084 SLOWLOG GET for Redis 4.0+
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/HostAndPort.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/util/Slowlog.java
  src/test/java/redis/clients/jedis/tests/commands/SlowlogCommandsTest.java
Labels: READY TO MERGE

#2254 JedisPubSub and BinaryJedisPubSub PING don't support optional argument
  src/main/java/redis/clients/jedis/BinaryJedisPubSub.java
  src/main/java/redis/clients/jedis/JedisPubSub.java
  src/test/java/redis/clients/jedis/tests/commands/PublishSubscribeCommandsTest.java
Labels: READY TO MERGE

#2292 Add support for new multi-key commands: SMISMEMBER and ZMSCORE
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/RedisPipeline.java
  src/test/java/redis/clients/jedis/tests/commands/SetCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
Labels: READY TO MERGE

#2157 (#2120) GeoRadius support store and storedist option with params
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/MultiKeyPipelineBase.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommandsPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyJedisClusterCommands.java
  src/main/java/redis/clients/jedis/params/GeoRadiusStoreParam.java
  src/test/java/redis/clients/jedis/tests/JedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/commands/GeoCommandsTest.java
Labels: READY TO MERGE

#2302 add support for ACL LOG command
  src/main/java/redis/clients/jedis/AccessControlLogEntry.java
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/AccessControlListCommandsTest.java
Labels: READY TO MERGE

#2028 Infinite Socket Timeout can be specified
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/JedisSlotBasedConnectionHandler.java
  src/test/java/redis/clients/jedis/tests/JedisTest.java
Labels: WAIT FOR MORE REVIEWS

#2309 Move XREAD and XREADGROUP methods in MultiKey... interfaces
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyJedisClusterCommands.java
Labels: BUG

#2319 Fixes missing parameters in JedisPool constructor
  src/main/java/redis/clients/jedis/JedisPool.java
Labels: BUG, WAIT FOR MORE REVIEWS

#2325 Update ACL tests and modify JedisPool tests
  Makefile
  src/main/java/redis/clients/jedis/JedisPool.java
  src/test/java/redis/clients/jedis/tests/JedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/JedisPoolWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/JedisTest.java
  src/test/java/redis/clients/jedis/tests/JedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/commands/AccessControlListCommandsTest.java
Labels: READY TO MERGE

#2313 refactor imports in commands package
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/main/java/redis/clients/jedis/commands/Commands.java
Labels: READY TO MERGE

#2304 Include Module test
  .circleci/config.yml
Labels: READY TO MERGE

#2321 A blocking version of sendCommand for Redis modules
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/BinaryValuesCommandsTest.java
Labels: READY TO MERGE
