Repository redis/jedis, pull requests merged in 2021-07, with the labels that each got.

#2573 Modify MEMORY USAGE tests
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2521 Pool extends GenericObjectPool
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/ShardedJedisPool.java
  src/main/java/redis/clients/jedis/util/Pool.java
  src/test/java/redis/clients/jedis/tests/JedisPoolTest.java
Labels: READY TO MERGE

#2578 Adjust ZRANDMEMBER test
  src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
Labels: BACKPORT IN PROGRESS

#2580 More HRANDFIELD tests
  src/test/java/redis/clients/jedis/tests/commands/HashesCommandsTest.java
Labels: BACKPORT IN PROGRESS

#2577 Minimal constructors with Config
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/test/java/redis/clients/jedis/tests/JedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisSentinelPoolTest.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2576 Warn Pool extends GenericObjectPool #2521
  src/main/java/redis/clients/jedis/util/Pool.java
Labels: READY TO MERGE

#2582 Test Sentinels with ACL
  Makefile
  pom.xml
  src/test/java/redis/clients/jedis/tests/HostAndPortUtil.java
  src/test/java/redis/clients/jedis/tests/JedisSentinelPoolWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisSentinelPoolTest.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2574 Fix Sentinel constructor
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2592 Test Busy exception
  src/test/java/redis/clients/jedis/tests/ExceptionsTest.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2587 Fix typo
  src/main/java/redis/clients/jedis/util/JedisClusterHashTagUtil.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2595 Address Javadoc Warnings
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/commands/BasicCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterBinaryScriptingCommands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterScriptingCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommands.java
Labels: BACKPORT IN PROGRESS, WAIT FOR MORE REVIEWS

#2591 CLIENT LIST command with TYPE argument
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/args/ClientType.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/params/ClientKillParams.java
  src/main/java/redis/clients/jedis/params/Params.java
  src/test/java/redis/clients/jedis/tests/commands/ClientCommandsTest.java
Labels: READY TO MERGE

#2598 Support EXECABORT Error
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/exceptions/AbortedTransactionException.java
  src/test/java/redis/clients/jedis/tests/ExceptionsTest.java
  src/test/java/redis/clients/jedis/tests/PipeliningTest.java
  src/test/java/redis/clients/jedis/tests/commands/JedisCommandTestBase.java
Labels: READY TO MERGE

#2588 Few more Sentinel commands
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/SentinelCommands.java
  src/test/java/redis/clients/jedis/tests/commands/SentinelCommandsTest.java
Labels: READY TO MERGE

#2599 Use assertSame to compare Class objects
  src/test/java/redis/clients/jedis/tests/ExceptionsTest.java
  src/test/java/redis/clients/jedis/tests/JedisTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/UnavailableConnectionTest.java
  src/test/java/redis/clients/jedis/tests/commands/TransactionCommandsTest.java
Labels: READY TO MERGE

#2601 CLIENT PAUSE command with mode option
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/args/ClientPauseMode.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#2605 More Cluster commands
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/ClusterReset.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/args/ClusterFailoverOption.java
  src/main/java/redis/clients/jedis/args/ClusterResetType.java
  src/main/java/redis/clients/jedis/commands/ClusterCommands.java
  src/test/java/redis/clients/jedis/tests/JedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/commands/ClusterCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#2607 ROLE command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#2610 FAILOVER command
  Makefile
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/main/java/redis/clients/jedis/params/FailoverParams.java
  src/test/java/redis/clients/jedis/tests/HostAndPortUtil.java
  src/test/java/redis/clients/jedis/tests/commands/FailoverCommandsTest.java
Labels: READY TO MERGE

#2609 Upgrade commons-pool to 2.10.0
  pom.xml
Labels: READY TO MERGE
