Repository redis/jedis, pull requests merged in 2021-03, with the labels that each got.

#2396 Fix parameter types and return types
  pom.xml
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/RedisPipeline.java
Labels: BUG, WAIT FOR MORE REVIEWS

#2399 EX param to long
  src/main/java/redis/clients/jedis/params/SetParams.java
Labels: READY TO MERGE

#2368 Introduce and extend Config pattern (III/2)
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/HostAndPortMapper.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java
  src/main/java/redis/clients/jedis/JedisClusterHostAndPortMap.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisSlotBasedConnectionHandler.java
  src/main/java/redis/clients/jedis/JedisSocketFactory.java
  src/test/java/redis/clients/jedis/tests/ConnectionTest.java
  src/test/java/redis/clients/jedis/tests/JedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/JedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/JedisPoolWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/JedisTest.java
  src/test/java/redis/clients/jedis/tests/JedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisClusterWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/ShardedJedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/ShardedJedisPoolWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/ShardedJedisTest.java
  src/test/java/redis/clients/jedis/tests/UdsTest.java
  src/test/java/redis/clients/jedis/tests/commands/AccessControlListCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#2402 Modify config pattern
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/test/java/redis/clients/jedis/tests/JedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/JedisTest.java
  src/test/java/redis/clients/jedis/tests/JedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisTest.java
Labels: WAIT FOR MORE REVIEWS

#2415 Add support INCR argument to ZADD command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
Labels: READY TO MERGE

#2417 Add support for getting Summary info by XPENDING
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/StreamPendingSummary.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
Labels: READY TO MERGE

#2418 Add support for ACL SAVE/LOAD commands
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/AccessControlListCommandsTest.java
Labels: READY TO MERGE

#2370 Added Rawable interface
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/args/Rawable.java
  src/main/java/redis/clients/jedis/commands/ProtocolCommand.java
Labels: READY TO MERGE

#2442 Add support for HRANDFIELD command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/RedisPipeline.java
  src/test/java/redis/clients/jedis/tests/commands/HashesCommandsTest.java
Labels: READY TO MERGE

#2315 Add ability to reset password in JedisFactory (II)
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisPoolAbstract.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/util/Pool.java
  src/test/java/redis/clients/jedis/tests/JedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/JedisPoolWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/JedisSentinelPoolTest.java
Labels: READY TO MERGE

#2424 Add support for clientUnblock command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/args/UnblockType.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/test/java/redis/clients/jedis/tests/commands/ClientCommandsTest.java
Labels: READY TO MERGE

#2305 XRead(Group) Params with allowing block=0
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyJedisClusterCommands.java
  src/main/java/redis/clients/jedis/params/XClaimParams.java
  src/main/java/redis/clients/jedis/params/XReadGroupParams.java
  src/main/java/redis/clients/jedis/params/XReadParams.java
  src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
Labels: BUG, READY TO MERGE

#2422 Rename socket timeout params and builder methods
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/test/java/redis/clients/jedis/tests/JedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/JedisPoolWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/JedisTest.java
  src/test/java/redis/clients/jedis/tests/JedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisWithCompleteCredentialsTest.java
Labels: READY TO MERGE

#2448 Add support for ZRANDMEMBER command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/RedisPipeline.java
  src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
Labels: READY TO MERGE

#2451 Add test case for handling consumername == NULL case in xpending
  src/main/java/redis/clients/jedis/Jedis.java
  src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
Labels: READY TO MERGE

#2201 Added Automatic-Module-Name to manifest
  pom.xml
Labels: WAIT FOR MORE REVIEWS

#2445 Support Sentinel with TLS (II/bc)
  Makefile
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/test/java/redis/clients/jedis/tests/SSLJedisSentinelPoolTest.java
Labels: READY TO MERGE

#2459 Add support for ZDIFF command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/MultiKeyPipelineBase.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommandsPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyJedisClusterCommands.java
  src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
Labels: READY TO MERGE

#2464 Add ASYNC/SYNC arg to FLUSHALL and FLUSHDB
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/MultiKeyPipelineBase.java
  src/main/java/redis/clients/jedis/args/FlushMode.java
  src/main/java/redis/clients/jedis/commands/BasicCommands.java
  src/main/java/redis/clients/jedis/commands/BasicRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/BinaryScriptingCommands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterBinaryScriptingCommands.java
  src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ClusterScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ScriptingCommandsTest.java
Labels: READY TO MERGE

#1928 Fixed the logic that prevents all cluster slot requests sent to specific instances
  src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java
Labels: READY TO MERGE

#2293 Add support to the use of JedisSocketFactory using a pool
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisSocketFactory.java
  src/test/java/redis/clients/jedis/tests/UdsTest.java
Labels: READY TO MERGE

#2481 Double timeout, avoid Tuple and more
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/KeyedTuple.java
  src/main/java/redis/clients/jedis/MultiKeyPipelineBase.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/args/package-info.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommandsPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyJedisClusterCommands.java
  src/main/java/redis/clients/jedis/resps/KeyedListElement.java
  src/main/java/redis/clients/jedis/resps/KeyedZSetElement.java
  src/main/java/redis/clients/jedis/resps/package-info.java
  src/test/java/redis/clients/jedis/tests/commands/ListCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
Labels: READY TO MERGE

#2393 Use IllegalStateException to replace invalid JedisDataException
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/Response.java
  src/main/java/redis/clients/jedis/util/SafeEncoder.java
  src/test/java/redis/clients/jedis/tests/JedisTest.java
  src/test/java/redis/clients/jedis/tests/JedisWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/PipeliningTest.java
  src/test/java/redis/clients/jedis/tests/ShardedJedisPipelineTest.java
  src/test/java/redis/clients/jedis/tests/commands/TransactionCommandsTest.java
Labels: READY TO MERGE

#2454 Avoid NullPointException from SetFromList class
  src/main/java/redis/clients/jedis/BinaryJedis.java
Labels: READY TO MERGE

#2409 JedisNoReachableClusterNodeException should extend JedisClusterOperationException (II)
  src/main/java/redis/clients/jedis/JedisClusterCommand.java
  src/main/java/redis/clients/jedis/JedisSlotBasedConnectionHandler.java
  src/main/java/redis/clients/jedis/exceptions/JedisClusterMaxAttemptsException.java
  src/main/java/redis/clients/jedis/exceptions/JedisNoReachableClusterNodeException.java
  src/test/java/redis/clients/jedis/tests/SSLJedisClusterTest.java
  src/test/java/redis/clients/jedis/tests/SSLJedisClusterWithCompleteCredentialsTest.java
Labels: READY TO MERGE
