Repository redis/jedis, pull requests merged in 2021-04, with the labels that each got.

#2492 Warn about Support Sentinel with TLS (II) #2403
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
Labels: WAIT FOR MORE REVIEWS

#2493 Warn about NoReachableNodeException extending ClusterOperationException #2409
  src/main/java/redis/clients/jedis/exceptions/JedisNoReachableClusterNodeException.java
Labels: WAIT FOR MORE REVIEWS

#2033 Remove WATCH from Transaction
  src/main/java/redis/clients/jedis/MultiKeyPipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/Transaction.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommandsPipeline.java
Labels: READY TO MERGE

#2498 XAUTOCLAIM Command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/main/java/redis/clients/jedis/commands/JedisClusterCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/RedisPipeline.java
  src/main/java/redis/clients/jedis/params/XAutoClaimParams.java
  src/test/java/redis/clients/jedis/tests/commands/StreamsCommandsTest.java
Labels: READY TO MERGE

#2506 fix cast exception on blpop
  src/main/java/redis/clients/jedis/Jedis.java
  src/test/java/redis/clients/jedis/tests/commands/ListCommandsTest.java
Labels: BACKPORT IN PROGRESS

#2502 Log remaining hidden exception in JedisFactory
  src/main/java/redis/clients/jedis/JedisFactory.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2501 JedisDataException should not be wrapped within Pool operations
  src/main/java/redis/clients/jedis/util/Pool.java
  src/test/java/redis/clients/jedis/tests/JedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/JedisPoolWithCompleteCredentialsTest.java
  src/test/java/redis/clients/jedis/tests/JedisSentinelPoolTest.java
Labels: READY TO MERGE

#2499 Remove SYNC command
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#2500 Remove ShardedJedisPipeline class
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/ShardedJedisPipeline.java
  src/test/java/redis/clients/jedis/tests/ShardedJedisPipelineTest.java
  src/test/java/redis/clients/jedis/tests/ShardedJedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/ShardedJedisPoolWithCompleteCredentialsTest.java
Labels: READY TO MERGE

#1734 Remove JedisPoolAbstract class, hide Pool.initPool() method and related changes
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisPoolAbstract.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/util/Pool.java
  src/test/java/redis/clients/jedis/tests/JedisPoolTest.java
  src/test/java/redis/clients/jedis/tests/JedisSentinelPoolTest.java
Labels: READY TO MERGE

#2507 Deprecate Remove SYNC command #2499
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Protocol.java
Labels: READY TO MERGE

#2516 Limit the access of setDataSource in Jedis
  src/main/java/redis/clients/jedis/Jedis.java
Labels: BACKPORT IN PROGRESS, READY TO MERGE

#2512 Test coverage: Jedis and BinaryJedis
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/BinaryValuesCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/BitCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/HyperLogLogCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/ScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/SlowlogCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/tests/commands/StringValuesCommandsTest.java
Labels: READY TO MERGE

#2514 Reduce lock granularity
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
Labels: BACKPORT IN PROGRESS, ENHANCEMENT, READY TO MERGE

#2522 Warn Limit the access of setDataSource in Jedis (#2516)
  src/main/java/redis/clients/jedis/Jedis.java
Labels: READY TO MERGE

#2525 CONFIG SET returns OK status (ii)
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/test/java/redis/clients/jedis/tests/commands/ControlCommandsTest.java
Labels: READY TO MERGE

#2526 private access for 'raw' and use getRaw()
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/ScanParams.java
Labels: READY TO MERGE
