Repository redis/jedis, pull requests merged in 2021-12, with the labels that each got.

#2709 Return List instead of Set where it makes sense
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/ClusterPipeline.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineCommands.java
  src/test/java/redis/clients/jedis/JedisClusterPipelineTest.java
  src/test/java/redis/clients/jedis/JedisClusterTest.java
  src/test/java/redis/clients/jedis/PipeliningTest.java
  src/test/java/redis/clients/jedis/ReliableTransactionTest.java
  src/test/java/redis/clients/jedis/TransactionV2Test.java
  src/test/java/redis/clients/jedis/TupleSortedSetTest.java
  src/test/java/redis/clients/jedis/commands/jedis/GeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/TransactionCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/VariadicCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/GeoCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterGeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterSortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/util/AssertUtil.java
Labels: breaking-change

#2682 Small fix in JedisClusterInfoCache.discoverClusterNodesAndSlots.
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
Labels: READY TO MERGE

#2689 support jedis migrate keys encoded by gdk
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/commands/ClusterCommands.java
  src/main/java/redis/clients/jedis/commands/Commands.java
  src/test/java/redis/clients/jedis/tests/commands/ClusterCommandsTest.java
Labels: READY TO MERGE

#2719 Support exclusive range in XRANGE command
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: WAIT FOR MORE REVIEWS, breaking-change

#2721 throw exception if JedisCluster cannot connect to any host-port
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
  src/test/java/redis/clients/jedis/JedisClusterWithoutSetupTest.java
  src/test/java/redis/clients/jedis/SSLACLJedisClusterTest.java
  src/test/java/redis/clients/jedis/SSLJedisClusterTest.java
Labels: WAIT FOR MORE REVIEWS

#2739 Bump log4j to 2.16.0
  pom.xml
Labels: testing

#2737 Address Jedis 4 breaking changes (in Jedis 3)
  src/main/java/redis/clients/jedis/BinaryClient.java
  src/main/java/redis/clients/jedis/BinaryJedis.java
  src/main/java/redis/clients/jedis/BinaryJedisCluster.java
  src/main/java/redis/clients/jedis/BinaryShardedJedis.java
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Client.java
  src/main/java/redis/clients/jedis/DebugParams.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/HostAndPort.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisShardInfo.java
  src/main/java/redis/clients/jedis/MultiKeyPipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/Queable.java
  src/main/java/redis/clients/jedis/ShardedJedis.java
  src/main/java/redis/clients/jedis/ShardedJedisPool.java
  src/main/java/redis/clients/jedis/Transaction.java
  src/main/java/redis/clients/jedis/commands/AdvancedBinaryJedisCommands.java
  src/main/java/redis/clients/jedis/commands/AdvancedJedisCommands.java
  src/main/java/redis/clients/jedis/commands/BasicCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryScriptingCommands.java
  src/main/java/redis/clients/jedis/commands/BinaryScriptingCommandsPipeline.java
  src/main/java/redis/clients/jedis/commands/JedisCommands.java
  src/main/java/redis/clients/jedis/commands/MultiKeyBinaryRedisPipeline.java
  src/main/java/redis/clients/jedis/commands/MultiKeyCommandsPipeline.java
  src/main/java/redis/clients/jedis/exceptions/JedisClusterMaxAttemptsException.java
  src/main/java/redis/clients/jedis/exceptions/JedisExhaustedPoolException.java
  src/main/java/redis/clients/jedis/exceptions/JedisNoReachableClusterNodeException.java
  src/main/java/redis/clients/jedis/params/SetParams.java
  src/main/java/redis/clients/jedis/util/JedisClusterHashTag.java
  src/main/java/redis/clients/jedis/util/JedisClusterHashTagUtil.java
  src/main/java/redis/clients/jedis/util/KeyMergeUtil.java
  src/main/java/redis/clients/jedis/util/Pool.java
  src/main/java/redis/clients/jedis/util/ShardInfo.java
  src/main/java/redis/clients/jedis/util/Sharded.java
  src/test/java/redis/clients/jedis/tests/commands/AccessControlListCommandsTest.java
Labels: READY TO MERGE

#2741 Remove deprecations that got remained
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/main/java/redis/clients/jedis/params/ClientKillParams.java
  src/main/java/redis/clients/jedis/util/Pool.java
  src/test/java/redis/clients/jedis/commands/jedis/ClientCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: READY TO MERGE

#2738 List the breaking changes from Jedis 3.x to Jedis 4.0
  docs/3to4-primitives.md
  docs/3to4-zset-list.md
  docs/3to4.md
Labels: READY TO MERGE

#2744 Remove Sentinel class
  docs/3to4.md
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/Sentinel.java
  src/test/java/redis/clients/jedis/JedisSentinelPoolTest.java
  src/test/java/redis/clients/jedis/JedisSentinelTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SentinelCommandsTest.java
  src/test/java/redis/clients/jedis/util/JedisSentinelTestUtil.java
Labels: READY TO MERGE

#2745 Resource withing cluster retry should be closed quietly
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
Labels: READY TO MERGE

#2753 Use slf4j-simple to replace log4j impl
  pom.xml
  src/test/java/redis/clients/jedis/JedisClusterTest.java
  src/test/java/redis/clients/jedis/ShardingTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/ListCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterListCommandsTest.java
  src/test/resources/MySimpson.png
  src/test/resources/log4j2.xml
Labels: READY TO MERGE

#2749 Replace deprecated interface with new interface of JedisPoolConfig
  src/main/java/redis/clients/jedis/ConnectionPoolConfig.java
  src/main/java/redis/clients/jedis/JedisPoolConfig.java
Labels: READY TO MERGE

#2765 Fix the zrevrangeByScore max/min parameter order problem in the transaction
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/test/java/redis/clients/jedis/TransactionV2Test.java
Labels: READY TO MERGE

#2763 Increase Coverage to ClusterPipeline and Responses classes
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/params/GeoRadiusParam.java
  src/main/java/redis/clients/jedis/resps/GeoRadiusResponse.java
  src/main/java/redis/clients/jedis/resps/KeyedListElement.java
  src/test/java/redis/clients/jedis/ClusterPipelineTest.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/TupleTest.java
  src/test/java/redis/clients/jedis/commands/jedis/GeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SlowlogCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
  src/test/java/redis/clients/jedis/resps/ResponsesToStringTest.java
  src/test/java/redis/clients/jedis/resps/TupleTest.java
Labels: READY TO MERGE

#2768 Added the BYTE|BIT option for bitcount (binary)
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/args/BitCountOption.java
  src/main/java/redis/clients/jedis/commands/StringBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/BitCommandsTest.java
Labels: READY TO MERGE

#2776 Support CLUSTER LINKS command
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/ClusterCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterCommandsTest.java
Labels: READY TO MERGE

#2771 Support GEOSEARCH and GEOSEARCHSTORE commands
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/GeoBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/GeoCommands.java
  src/main/java/redis/clients/jedis/commands/GeoPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/GeoPipelineCommands.java
  src/main/java/redis/clients/jedis/params/GeoSearchParam.java
  src/test/java/redis/clients/jedis/commands/jedis/GeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/GeoCommandsTestBase.java
Labels: READY TO MERGE

#2746 Support XINFO STREAM FULL
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StreamBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamGroupFullInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: READY TO MERGE
