Repository redis/jedis, pull requests merged in 2022-12, with the labels that each got.

#3210 Adding Javadocs to Jedis 'args' package
  src/main/java/redis/clients/jedis/args/BitCountOption.java
  src/main/java/redis/clients/jedis/args/BitOP.java
  src/main/java/redis/clients/jedis/args/ClientPauseMode.java
  src/main/java/redis/clients/jedis/args/ClusterFailoverOption.java
  src/main/java/redis/clients/jedis/args/ClusterResetType.java
  src/main/java/redis/clients/jedis/args/ExpiryOption.java
  src/main/java/redis/clients/jedis/args/Rawable.java
  src/main/java/redis/clients/jedis/args/RawableFactory.java
Labels: maintenance

#3221 Support pipelining from UnifiedJedis
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/JedisSharding.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledBinaryValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledBitCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledGeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledHashesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledHyperLogLogCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledPipelinedTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledSortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledStringValuesCommandsTest.java
Labels: ready to merge, enhancement

#3225 Update test system setup
  .github/workflows/integration.yml
  Makefile
Labels: testing, maintenance

#3227 Polish #3194: Method renamed to broadcast()
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterValuesCommandsTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: enhancement

#3162 Add dependabot configuration
  .github/dependabot.yml
Labels: maintenance

#3236 Support BITPOS command with BYTE|BIT modifier
  src/main/java/redis/clients/jedis/params/BitPosParams.java
  src/test/java/redis/clients/jedis/commands/jedis/BitCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/BitCommandsTestBase.java
Labels: enhancement

#3237 Support CLIENT UNPAUSE command
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/ClientBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/ClientCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
Labels: wait for more reviews, enhancement

#3239 Support LATENCY DOCTOR command
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/ServerCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
Labels: feature

#3243 Test: Reduce flaky-ness of CLIENT PAUSE tests
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
Labels: testing, maintenance

#3223 Allow exclusion of GSON dependency
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/GsonJson.java
Labels: maintenance

#3242 Make org.json safely replace-able with android-json
  src/main/java/redis/clients/jedis/BuilderFactory.java
Labels: maintenance

#3246 Test: Intermediate sync() works in regular Pipeline
  src/test/java/redis/clients/jedis/PipeliningTest.java
Labels: testing

#3226 Support intermediate sync() calls in multi node pipelines
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
Labels: ready to merge, enhancement

#3240 Support Sentinel mode with UnifiedJedis
  src/main/java/redis/clients/jedis/JedisSentineled.java
  src/main/java/redis/clients/jedis/providers/SentineledConnectionProvider.java
  src/test/java/redis/clients/jedis/JedisSentinelPoolTest.java
  src/test/java/redis/clients/jedis/SentineledConnectionProviderTest.java
Labels: feature

#3253 Get Object from aggregation Row
  src/main/java/redis/clients/jedis/search/aggr/AggregationResult.java
  src/main/java/redis/clients/jedis/search/aggr/Row.java
  src/test/java/redis/clients/jedis/modules/search/AggregationBuilderTest.java
Labels: experimental

#3229 Add snapshot link in readme
  README.md
Labels: documentation
