Repository redis/jedis, pull requests merged in 2022-08, with the labels that each got.

#3094 Fix NPE when stream pending message is discarded
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: backport in progress, BUG

#3104 UnifiedJedis can use a custom CommandExecutor
  src/main/java/redis/clients/jedis/UnifiedJedis.java
Labels: enhancement

#3116 Support remaining TS.ALTER params
  src/main/java/redis/clients/jedis/timeseries/TSAlterParams.java
  src/main/java/redis/clients/jedis/timeseries/TSCreateParams.java
  src/main/java/redis/clients/jedis/timeseries/TSInfo.java
  src/test/java/redis/clients/jedis/modules/timeseries/TimeSeriesTest.java
Labels: enhancement

#3124 Add restrictions while setting search field attribute
  src/main/java/redis/clients/jedis/search/FieldName.java
  src/test/java/redis/clients/jedis/modules/search/SchemaTest.java
Labels: breakingchange
