Repository redis/jedis, pull requests merged in 2022-09, with the labels that each got.

#3120 Re-work FT.CREATE and FT.ALTER
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FTCreateParams.java
  src/main/java/redis/clients/jedis/search/FieldName.java
  src/main/java/redis/clients/jedis/search/IndexDataType.java
  src/main/java/redis/clients/jedis/search/RediSearchCommands.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/main/java/redis/clients/jedis/search/schemafields/GeoField.java
  src/main/java/redis/clients/jedis/search/schemafields/NumericField.java
  src/main/java/redis/clients/jedis/search/schemafields/SchemaField.java
  src/main/java/redis/clients/jedis/search/schemafields/TagField.java
  src/main/java/redis/clients/jedis/search/schemafields/TextField.java
  src/main/java/redis/clients/jedis/search/schemafields/VectorField.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
  src/test/java/redis/clients/jedis/util/AssertUtil.java
Labels: experimental

#3107 Include QueryBuilder implementations
  src/main/java/redis/clients/jedis/search/querybuilder/DisjunctNode.java
  src/main/java/redis/clients/jedis/search/querybuilder/DisjunctUnionNode.java
  src/main/java/redis/clients/jedis/search/querybuilder/DoubleRangeValue.java
  src/main/java/redis/clients/jedis/search/querybuilder/GeoValue.java
  src/main/java/redis/clients/jedis/search/querybuilder/IntersectNode.java
  src/main/java/redis/clients/jedis/search/querybuilder/LongRangeValue.java
  src/main/java/redis/clients/jedis/search/querybuilder/Node.java
  src/main/java/redis/clients/jedis/search/querybuilder/OptionalNode.java
  src/main/java/redis/clients/jedis/search/querybuilder/QueryBuilders.java
  src/main/java/redis/clients/jedis/search/querybuilder/QueryNode.java
  src/main/java/redis/clients/jedis/search/querybuilder/RangeValue.java
  src/main/java/redis/clients/jedis/search/querybuilder/UnionNode.java
  src/main/java/redis/clients/jedis/search/querybuilder/Value.java
  src/main/java/redis/clients/jedis/search/querybuilder/ValueNode.java
  src/main/java/redis/clients/jedis/search/querybuilder/Values.java
  src/test/java/redis/clients/jedis/modules/search/QueryBuilderTest.java
Labels: experimental

#3134 Better binary support for SET command with GET option
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StringBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineCommands.java
  src/main/java/redis/clients/jedis/params/SetParams.java
  src/test/java/redis/clients/jedis/PipeliningTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/BinaryValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/AllKindOfValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/BinaryValuesCommandsTestBase.java
Labels: enhancement

#3135 Add SortingOrder argument
  src/main/java/redis/clients/jedis/args/SortingOrder.java
  src/main/java/redis/clients/jedis/params/GeoRadiusParam.java
  src/main/java/redis/clients/jedis/params/GeoSearchParam.java
  src/main/java/redis/clients/jedis/params/SortingParams.java
Labels: enhancement

#3136 Deprecate ASC and DESC keywords
  src/main/java/redis/clients/jedis/Protocol.java
Labels: maintenance

#3139 Test ClusterCommandExecutor
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
  src/main/java/redis/clients/jedis/executors/RetryableCommandExecutor.java
  src/test/java/redis/clients/jedis/ClusterCommandExecutorTest.java
Labels: testing, maintenance

#3143 Cleanup broken connection from ClusterPipeline
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
Labels: backport required, BUG

#3118 Makes getBackoffSleepMillis in ClusterCommandExecutor nondeterministic
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
Labels: WAIT FOR MORE REVIEWS

#3138 Re-work FT.SEARCH
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FTCreateParams.java
  src/main/java/redis/clients/jedis/search/FTSearchParams.java
  src/main/java/redis/clients/jedis/search/IndexDefinition.java
  src/main/java/redis/clients/jedis/search/LazyRawable.java
  src/main/java/redis/clients/jedis/search/Query.java
  src/main/java/redis/clients/jedis/search/RediSearchCommands.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationResult.java
  src/main/java/redis/clients/jedis/search/schemafields/TagField.java
  src/main/java/redis/clients/jedis/util/KeyValue.java
  src/test/java/redis/clients/jedis/modules/search/AggregationBuilderTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental

#3112 Separate package for RedisBloom commands
  src/main/java/redis/clients/jedis/bloom/commands/BloomFilterCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/BloomFilterPipelineCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/CountMinSketchCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/CountMinSketchPipelineCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/CuckooFilterCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/CuckooFilterPipelineCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/RedisBloomCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/RedisBloomPipelineCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TDigestSketchCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TDigestSketchPipelineCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterPipelineCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/package-info.java
  src/main/java/redis/clients/jedis/bloom/package-info.java
  src/main/java/redis/clients/jedis/commands/RedisModuleCommands.java
  src/main/java/redis/clients/jedis/commands/RedisModulePipelineCommands.java
  src/test/java/redis/clients/jedis/modules/bloom/TDigestTest.java
Labels: breakingchange, maintenance

#3144 Defaulting the release drafter to minor version
  .github/release-drafter-config.yml
Labels: maintenance

#3145 Publishing snapshots only on merge to active branches
  .github/workflows/snapshot.yml
Labels: maintenance

#3149 [Test] Address ACL.GETUSER change(s)
  pom.xml
  src/test/java/redis/clients/jedis/commands/jedis/AccessControlListCommandsTest.java
Labels: testing, maintenance

#3148 Fix null property value parsing of search document
  src/main/java/redis/clients/jedis/search/Document.java
  src/main/java/redis/clients/jedis/search/SearchResult.java
  src/test/java/redis/clients/jedis/modules/search/JsonSearchWithGsonTest.java
Labels: backport required, BUG

#3150 Improve jedis.get doc
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/commands/StringCommands.java
Labels: documentation

#3155 fix: #3154 validate host and port of jedis connection
  src/main/java/redis/clients/jedis/JedisFactory.java
Labels: BUG
