Repository redis/jedis, pull requests merged in 2022-07, with the labels that each got.

#3054 Extend support to all arguments of FT.SEARCH and FT.AGGREGATE commands
  src/main/java/redis/clients/jedis/search/Query.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationBuilder.java
  src/test/java/redis/clients/jedis/modules/search/AggregationBuilderTest.java
  src/test/java/redis/clients/jedis/modules/search/JsonSearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
Labels: enhancement

#3071 Update README.md
  README.md
Labels: maintenance

#3079 Activate basic Graph/ResultSet/Statistics tests
  src/test/java/redis/clients/jedis/modules/graph/GraphAPITest.java
Labels: testing, maintenance

#3082 Support new TimeSeries arguments
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/timeseries/AggregationType.java
  src/main/java/redis/clients/jedis/timeseries/RedisTimeSeriesCommands.java
  src/main/java/redis/clients/jedis/timeseries/RedisTimeSeriesPipelineCommands.java
  src/main/java/redis/clients/jedis/timeseries/TSAlterParams.java
  src/main/java/redis/clients/jedis/timeseries/TSCreateParams.java
  src/main/java/redis/clients/jedis/timeseries/TSGetParams.java
  src/main/java/redis/clients/jedis/timeseries/TSMGetParams.java
  src/main/java/redis/clients/jedis/timeseries/TSMRangeParams.java
  src/main/java/redis/clients/jedis/timeseries/TSRangeParams.java
  src/main/java/redis/clients/jedis/timeseries/TimeSeriesProtocol.java
  src/test/java/redis/clients/jedis/modules/timeseries/TimeSeriesTest.java
Labels: enhancement

#3085 Preserve order in responses of ZDIFF, ZINTER, ZUNION commands
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
Labels: BUG

#3089 pre-allocate the results size
  src/main/java/redis/clients/jedis/graph/ResultSetBuilder.java
Labels: enhancement

#3090 Optimize Entities capacity to avoid reallocation
  src/main/java/redis/clients/jedis/graph/ResultSetBuilder.java
  src/main/java/redis/clients/jedis/graph/entities/Edge.java
  src/main/java/redis/clients/jedis/graph/entities/GraphEntity.java
  src/main/java/redis/clients/jedis/graph/entities/Node.java
Labels: enhancement
