Repository redis/jedis, pull requests merged in 2022-11, with the labels that each got.

#3188 Support FT.PROFILE command
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FTProfileParams.java
  src/main/java/redis/clients/jedis/search/RediSearchCommands.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental

#3197 Support FT._LIST command: ftList() method
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/RediSearchCommands.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental

#3195 Address empty cluster slots list when discovering slots
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
Labels: WAIT FOR MORE REVIEWS, enhancement

#3208 Test: Address memory optimizations in Redis List
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ObjectCommandsTest.java
Labels: testing, maintenance

#3204 Javadocs in Exception classes
  src/main/java/redis/clients/jedis/exceptions/JedisAccessControlException.java
  src/main/java/redis/clients/jedis/exceptions/JedisAskDataException.java
  src/main/java/redis/clients/jedis/exceptions/JedisBusyException.java
  src/main/java/redis/clients/jedis/exceptions/JedisClusterException.java
  src/main/java/redis/clients/jedis/exceptions/JedisClusterOperationException.java
  src/main/java/redis/clients/jedis/exceptions/JedisConnectionException.java
  src/main/java/redis/clients/jedis/exceptions/JedisDataException.java
  src/main/java/redis/clients/jedis/exceptions/JedisException.java
  src/main/java/redis/clients/jedis/exceptions/JedisMovedDataException.java
  src/main/java/redis/clients/jedis/exceptions/JedisNoScriptException.java
  src/main/java/redis/clients/jedis/exceptions/JedisRedirectionException.java
Labels: READY TO MERGE, maintenance

#3200 Fix RedisJSON doc for POJOs
  docs/redisjson.md
Labels: documentation

#3209 Test: Debug cluster executor test fail
  src/test/java/redis/clients/jedis/ClusterCommandExecutorTest.java
Labels: testing, maintenance
