Repository redis/jedis, pull requests merged in 2022-04, with the labels that each got.

#2968 [QUICK FIX] A RediSearch command must be sent to a master node
  src/main/java/redis/clients/jedis/ClusterCommandObjects.java
Labels: BUG

#2972 Correct commandarguments for zrevrangebyscore
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
Labels: BUG

#2988 Fix PENDING entries of xinfoStreamFull method
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamGroupFullInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: READY TO MERGE, BUG, breaking-change

#2990 Fix: return of CLUSTER REPLICAS is Array reply
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/commands/ClusterCommands.java
Labels: BUG, breaking-change
