Repository redis/jedis, pull requests merged in 2022-10, with the labels that each got.

#3156 Address TDIGEST.ADD changes
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/bloom/commands/TDigestSketchCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TDigestSketchPipelineCommands.java
  src/test/java/redis/clients/jedis/modules/bloom/TDigestTest.java
Labels: breakingchange, experimental

#3158 Support TDIGEST.[BY][REV]RANK commands
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/bloom/RedisBloomProtocol.java
  src/main/java/redis/clients/jedis/bloom/commands/TDigestSketchCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TDigestSketchPipelineCommands.java
  src/test/java/redis/clients/jedis/modules/bloom/TDigestTest.java
Labels: experimental

#3160 Upgrade SLF4J to 1.7.36
  pom.xml
Labels: dependencies, maintenance

#3161 Upgrade org.JSON to 20220320
  pom.xml
Labels: dependencies, maintenance

#3165 Address TDIGEST.INFO changes
  src/test/java/redis/clients/jedis/modules/bloom/TDigestTest.java
Labels: testing

#3166 Catch JedisException in loop instead of JCE
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
Labels: BUG

#3167 Deprecate TOPK.COUNT command
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterPipelineCommands.java
Labels: maintenance

#3168 Test: Address TDIGEST.BYREVRANK changes
  src/test/java/redis/clients/jedis/modules/bloom/TDigestTest.java
Labels: testing

#3170 Test: Address ACL error messaging changes
  src/test/java/redis/clients/jedis/commands/jedis/AccessControlListCommandsTest.java
Labels: testing

#3169 Add ability to pass ClusterConnectionProvider to JedisCluster
  src/main/java/redis/clients/jedis/JedisCluster.java
Labels: enhancement

#3173 Release drafter formatting improvement: titles
  .github/release-drafter-config.yml
Labels: maintenance

#3174 Address JavaDoc warnings
  src/main/java/redis/clients/jedis/bloom/commands/CountMinSketchCommands.java
  src/main/java/redis/clients/jedis/commands/ListCommands.java
  src/main/java/redis/clients/jedis/graph/entities/Property.java
Labels: maintenance

#3175 Support FT.SPELLCHECK command
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FTSpellCheckParams.java
  src/main/java/redis/clients/jedis/search/RediSearchCommands.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SpellCheckTest.java
Labels: experimental

#3176 Test: graph parser can handle inf, nan, etc
  src/test/java/redis/clients/jedis/modules/graph/GraphValuesTest.java
Labels: testing

#3177 Test: Address TDIGEST.RANK changes
  src/test/java/redis/clients/jedis/modules/bloom/TDigestTest.java
Labels: testing

#3184 Test: Address DEFAULT_DIALECT search config change
  src/test/java/redis/clients/jedis/modules/search/SearchConfigTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
Labels: testing, maintenance

#3183 Easy PooledConnectionProvider with GenericObjectPoolConfig
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/providers/PooledConnectionProvider.java
Labels: enhancement

#3185 Fix JedisPooled constructors missing poolConfig param
  src/main/java/redis/clients/jedis/JedisPooled.java
Labels: backport required, BUG

#3186 Refactor GenericObjectPool usages
  src/main/java/redis/clients/jedis/ConnectionPool.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisPool.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/providers/PooledConnectionProvider.java
  src/main/java/redis/clients/jedis/providers/ShardedConnectionProvider.java
  src/main/java/redis/clients/jedis/util/Pool.java
Labels: enhancement, maintenance
