Repository redis/jedis, pull requests merged in 2023-09, with the labels that each got.

#3524 Disabling doctests on tag
  .github/workflows/doctests.yml
Labels: maintenance

#3509 Extend CLIENT SETINFO support
  src/main/java/redis/clients/jedis/ClientSetInfoConfig.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/DefaultClientSetInfoConfig.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/util/JedisMetaInfo.java
  src/test/java/redis/clients/jedis/JedisTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ClientCommandsTest.java
Labels: ready to merge, backport required, enhancement

#3536 Address further CLIENT SETINFO suffix rules
  src/main/java/redis/clients/jedis/ClientSetInfoConfig.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/DefaultClientSetInfoConfig.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/test/java/redis/clients/jedis/JedisTest.java
  src/test/java/redis/clients/jedis/misc/ClientSetInfoConfigTest.java
Labels: feature

#3542 Added JavaDoc for GeoRadiusResponse
  src/main/java/redis/clients/jedis/resps/GeoRadiusResponse.java
Labels: documentation

#3549 Re-add FT.DROPINDEX and FT.ALTER in pipeline
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/RediSearchCommands.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
Labels: experimental

#3531 Feature: Triggers and functions commands
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/RedisModuleCommands.java
  src/main/java/redis/clients/jedis/gears/RedisGearsCommands.java
  src/main/java/redis/clients/jedis/gears/RedisGearsProtocol.java
  src/main/java/redis/clients/jedis/gears/TFunctionListParams.java
  src/main/java/redis/clients/jedis/gears/TFunctionLoadParams.java
  src/main/java/redis/clients/jedis/gears/resps/FunctionInfo.java
  src/main/java/redis/clients/jedis/gears/resps/FunctionStreamInfo.java
  src/main/java/redis/clients/jedis/gears/resps/GearsLibraryInfo.java
  src/main/java/redis/clients/jedis/gears/resps/StreamTriggerInfo.java
  src/main/java/redis/clients/jedis/gears/resps/TriggerInfo.java
  src/test/java/redis/clients/jedis/modules/gears/GearsTest.java
  src/test/resources/functions/keyspaceTriggers.js
  src/test/resources/functions/pingpong.js
  src/test/resources/functions/streamTriggers.js
  src/test/resources/functions/withConfig.js
  src/test/resources/functions/withFlags.js
  src/test/resources/functions/workingWIthHashes.js
Labels: feature

#3551 Polish Feature: Triggers and functions commands
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandArguments.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/gears/RedisGearsCommands.java
  src/main/java/redis/clients/jedis/gears/RedisGearsProtocol.java
  src/main/java/redis/clients/jedis/gears/TFunctionListParams.java
  src/main/java/redis/clients/jedis/gears/TFunctionLoadParams.java
  src/main/java/redis/clients/jedis/gears/resps/GearsLibraryInfo.java
  src/main/java/redis/clients/jedis/resps/LibraryInfo.java
  src/test/java/redis/clients/jedis/modules/gears/GearsTest.java
Labels: maintenance

#3552 Fix Search/Gears test regression
  src/test/java/redis/clients/jedis/modules/gears/GearsTest.java
Labels: testing

#3553 Different variable names for json v1 and v2 interfaces
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV1Test.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV2Test.java
Labels: testing

#3554 Polish Triggers and functions tests
  src/main/java/redis/clients/jedis/gears/resps/GearsLibraryInfo.java
  src/test/java/redis/clients/jedis/modules/gears/GearsTest.java
Labels: testing

#3555 Encode map in encoded object
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/test/java/redis/clients/jedis/modules/gears/GearsTest.java
Labels: breakingchange, maintenance

#3557 Broadcast FUNCTION LOAD command methods
  src/main/java/redis/clients/jedis/UnifiedJedis.java
Labels: backport required, feature, docs-review
