Repository redis/jedis, pull requests merged in 2023-11, with the labels that each got.

#3015 Support RESET command
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/ServerCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
Labels: backport required, feature

#3596 Introducing periodic topology mechanism for JedisCluster
  Makefile
  src/main/java/redis/clients/jedis/ClusterPipeline.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
  src/test/java/redis/clients/jedis/JedisClusterTest.java
  src/test/java/redis/clients/jedis/JedisClusterTestBase.java
Labels: ready to merge, backport required, feature

#3605 Added HSET variants to ease complex objects
  src/main/java/redis/clients/jedis/CommandArguments.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: backport required, feature

#3598 Add CLUSTER SHARDS command support (#2984)
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/ClusterCommands.java
  src/main/java/redis/clients/jedis/resps/ClusterShardInfo.java
  src/main/java/redis/clients/jedis/resps/ClusterShardNodeInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterCommandsTest.java
Labels: feature

#3615 Rename 'activeactive' package to 'mcf'
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverBase.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverConnectionProvider.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterPipeline.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterTransaction.java
  src/main/java/redis/clients/jedis/mcf/package-info.java
Labels: maintenance

#3636 Address RediSearch profile change
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: backport required, testing

#3637 Access Reducer attributes
  src/main/java/redis/clients/jedis/search/aggr/Reducer.java
  src/test/java/redis/clients/jedis/modules/search/AggregationBuilderTest.java
Labels: maintenance
