Repository redis/jedis, pull requests merged in 2023-02, with the labels that each got.

#3289 Migration from deprecated Long constructor
  src/test/java/redis/clients/jedis/PipeliningTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ObjectCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/PublishSubscribeCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ScriptingCommandsTest.java
Labels: testing

#3290 Fix jedis#hdel docs
  src/main/java/redis/clients/jedis/Jedis.java
  src/test/java/redis/clients/jedis/commands/jedis/HashesCommandsTest.java
Labels: testing, documentation

#3224 Introduce credentials provider
  src/main/java/redis/clients/jedis/CommandArguments.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/DefaultRedisCredentials.java
  src/main/java/redis/clients/jedis/DefaultRedisCredentialsProvider.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/RedisCredentials.java
  src/main/java/redis/clients/jedis/RedisCredentialsProvider.java
  src/test/java/redis/clients/jedis/JedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPooledTest.java
  src/test/java/redis/clients/jedis/SentineledConnectionProviderTest.java
  src/test/java/redis/clients/jedis/examples/RedisCredentialsProviderExample.java
Labels: ready to merge, enhancement

#3301 Fix SELECT command in Pipeline
  src/main/java/redis/clients/jedis/Pipeline.java
  src/test/java/redis/clients/jedis/PipeliningTest.java
Labels: backport required, bug

#3302 Add simple JedisCluster constructor with HostAndPortMapper
  src/main/java/redis/clients/jedis/JedisCluster.java
Labels: backport required, enhancement

#3285 OSS Broadcast support
  README.md
  src/main/java/redis/clients/jedis/BroadcastResponse.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/JedisBroadcast.java
  src/main/java/redis/clients/jedis/JedisBroadcastAndRoundRobinConfig.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/exceptions/JedisBroadcastException.java
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
  src/main/java/redis/clients/jedis/executors/CommandExecutor.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterValuesCommandsTest.java
  src/test/java/redis/clients/jedis/examples/BroadcastCommandsToAllClusterNodes.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental

#3306 Broadcast commands listed in #3303
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/DatabaseCommands.java
  src/main/java/redis/clients/jedis/commands/ServerCommands.java
Labels: breakingchange, experimental
