Repository redis/jedis, pull requests merged in 2023-04, with the labels that each got.

#3322 Adding redis version compatibility details to the README
  README.md
Labels: documentation

#3351 Move version compatibility outside Getting started
  README.md
Labels: documentation

#3353 Avoid using QUIT command
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/ServerCommands.java
Labels: ready to merge, backport required

#3357 Fix test with issue hidden due to optional client name
  src/test/java/redis/clients/jedis/JedisPooledTest.java
Labels: testing

#3334 Introduce round-robining for scan and ft.search commands
  src/main/java/redis/clients/jedis/ScanRoundRobin.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FtSearchRoundRobin.java
  src/main/java/redis/clients/jedis/util/JedisRoundRobinBase.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/AllKindOfValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental

#3358 Support round-robining for ft.aggregate command
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FtSearchRoundRobin.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationBuilder.java
  src/main/java/redis/clients/jedis/search/aggr/FtAggregateRoundRobin.java
  src/test/java/redis/clients/jedis/modules/search/AggregationTest.java
Labels: experimental

#3359 Support round-robining for timeseries commands
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/timeseries/TsMGetRoundRobin.java
  src/main/java/redis/clients/jedis/timeseries/TsMRangeRoundRobin.java
  src/test/java/redis/clients/jedis/modules/timeseries/TimeSeriesTest.java
Labels: experimental

#3361 Support 'multi()' from JedisPooled (UnifiedJedis)
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisSharding.java
  src/main/java/redis/clients/jedis/ReliableTransaction.java
  src/main/java/redis/clients/jedis/Transaction.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledPipeliningTest.java
Labels: enhancement

#3362 Fix GraphCommandObjects in multi node
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/graph/GraphCommandObjects.java
  src/main/java/redis/clients/jedis/graph/GraphQueryParams.java
Labels: bug

#3367 Support client no-touch command
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/commands/ClientCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
Labels: enhancement

#3375 FT.SEARCH, FT.AGGREGATE, etc commands are round robin mode by default
  src/main/java/redis/clients/jedis/ClusterCommandObjects.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
Labels: breakingchange, experimental

#3378 Support iteration for SCAN, FT.SEARCH, FT.AGGREGATE commands
  src/main/java/redis/clients/jedis/ScanIteration.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FtSearchIteration.java
  src/main/java/redis/clients/jedis/search/aggr/FtAggregateIteration.java
  src/main/java/redis/clients/jedis/util/JedisCommandIterationBase.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/AllKindOfValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/modules/search/AggregationTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental

#3364 Support Z[REV]RANK command with score option
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
Labels: ready to merge

#3373 Performance improvement cluster slots slotNodes cache switch hashmap to arrays
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
Labels: ready to merge

#3381 Newly disconnected connections are set as broken
  src/main/java/redis/clients/jedis/Connection.java
Labels: backport required, maintenance
