Repository redis/jedis, pull requests merged in 2023-01, with the labels that each got.

#3263 Including startup instructions via redis-stack docker
  README.md
Labels: maintenance

#3262 Improved Transaction classes documentation
  src/main/java/redis/clients/jedis/ReliableTransaction.java
  src/main/java/redis/clients/jedis/Transaction.java
  src/main/java/redis/clients/jedis/TransactionBase.java
Labels: documentation, maintenance

#3273 Upgrade JUnixSocket Core to 2.6.1
  pom.xml
Labels: dependencies, testing

#3275 Support BF.CARD command
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/bloom/RedisBloomProtocol.java
  src/main/java/redis/clients/jedis/bloom/commands/BloomFilterCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/BloomFilterPipelineCommands.java
  src/test/java/redis/clients/jedis/modules/bloom/BloomTest.java
Labels: enhancement, experimental

#3249 Allow exclusion of org.json dependency
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/JsonBuilderFactory.java
Labels: breakingchange, maintenance

#3272 Upgrade Gson to 2.10.1
  pom.xml
Labels: dependencies

#3274 Added a suppressed exception in cluster initialization
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
  src/test/java/redis/clients/jedis/JedisClusterWithoutSetupTest.java
Labels: ready to merge, enhancement

#3279 Separate interfaces for bit commands
  src/main/java/redis/clients/jedis/commands/BitBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/BitCommands.java
  src/main/java/redis/clients/jedis/commands/BitPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/BitPipelineCommands.java
  src/main/java/redis/clients/jedis/commands/StringBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineCommands.java
Labels: enhancement
