Repository redis/jedis, pull requests merged in 2023-05, with the labels that each got.

#3389 Re-use Pub/Sub codes
  src/main/java/redis/clients/jedis/BinaryJedisPubSub.java
  src/main/java/redis/clients/jedis/JedisPubSub.java
  src/main/java/redis/clients/jedis/JedisPubSubBase.java
  src/test/java/redis/clients/jedis/commands/jedis/PublishSubscribeCommandsTest.java
Labels: breakingchange

#3391 Cleanup deprecations for Jedis 5.0
  src/main/java/redis/clients/jedis/CommandArguments.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisSentineled.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/bloom/RedisBloomProtocol.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterPipelineCommands.java
  src/main/java/redis/clients/jedis/commands/ServerCommands.java
  src/main/java/redis/clients/jedis/commands/StreamBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/main/java/redis/clients/jedis/commands/StringBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineCommands.java
  src/main/java/redis/clients/jedis/graph/GraphQueryParams.java
  src/main/java/redis/clients/jedis/params/SetParams.java
  src/main/java/redis/clients/jedis/params/StrAlgoLCSParams.java
  src/main/java/redis/clients/jedis/params/XPendingParams.java
  src/main/java/redis/clients/jedis/search/Document.java
  src/main/java/redis/clients/jedis/search/FieldName.java
  src/main/java/redis/clients/jedis/search/FtSearchIteration.java
  src/main/java/redis/clients/jedis/search/IndexDefinition.java
  src/main/java/redis/clients/jedis/search/Query.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
  src/main/java/redis/clients/jedis/search/Schema.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/main/java/redis/clients/jedis/search/SearchResult.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationBuilder.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationResult.java
  src/main/java/redis/clients/jedis/timeseries/TSAlterParams.java
  src/test/java/redis/clients/jedis/ACLJedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPooledTest.java
  src/test/java/redis/clients/jedis/JedisSentinelPoolTest.java
  src/test/java/redis/clients/jedis/ShardedConnectionTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/BinaryValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/StringValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/AllKindOfValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/BinaryValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/StringValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/modules/RedisModulesPipelineTest.java
  src/test/java/redis/clients/jedis/modules/bloom/TopKTest.java
  src/test/java/redis/clients/jedis/modules/search/AggregationTest.java
  src/test/java/redis/clients/jedis/modules/search/DocumentTest.java
  src/test/java/redis/clients/jedis/modules/search/JsonSearchTest.java
Labels: breakingchange

#3399 More RESP3 breaking and testing changes
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/ShardedPipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/resps/AccessControlLogEntry.java
  src/test/java/redis/clients/jedis/JedisTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledCommandsTestHelper.java
  src/test/java/redis/clients/jedis/modules/RedisModuleCommandsTestBase.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: breakingchange

#3400 Changing to the right edge docker set
  .github/workflows/integration.yml
Labels: maintenance

#3401 Use Matchers instead of CoreMatchers
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/PipeliningTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AccessControlListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ObjectCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV1Test.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV2Test.java
  src/test/java/redis/clients/jedis/modules/search/SchemaTest.java
  src/test/java/redis/clients/jedis/modules/search/SpellCheckTest.java
  src/test/java/redis/clients/jedis/resps/ResponsesToStringTest.java
  src/test/java/redis/clients/jedis/resps/TupleTest.java
Labels: testing

#3403 Support RESP3 protocol through URI/URL
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/RedisProtocol.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/util/JedisURIHelper.java
  src/test/java/redis/clients/jedis/ACLJedisTest.java
  src/test/java/redis/clients/jedis/JedisTest.java
  src/test/java/redis/clients/jedis/SSLACLJedisTest.java
  src/test/java/redis/clients/jedis/SSLJedisTest.java
  src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java
Labels: feature

#3415 List Jedis 5.0 breaking changes
  docs/3to4.md
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerInfo.java
  src/main/java/redis/clients/jedis/resps/StreamFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamGroupFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamGroupInfo.java
  src/main/java/redis/clients/jedis/resps/StreamInfo.java
  src/main/java/redis/clients/jedis/util/DoublePrecision.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: breakingchange, documentation

#3418 Redis.io code examples
  .github/CONTRIBUTING.md
  .github/workflows/doctests.yml
  pom.xml
  src/test/java/io/redis/examples/SearchQuickstartExample.java
  src/test/java/io/redis/examples/SetGetExample.java
  src/test/java/redis/clients/jedis/examples/RedisCredentialsProviderUsage.java
Labels: documentation

#3411 Fix: client setname need ignore syntax error in redis4
  src/main/java/redis/clients/jedis/Connection.java
Labels: bug

#3421 Update XINFO STREAM reply
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerFullInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: enhancement

#3422 Update XINFO CONSUMERS reply
  src/main/java/redis/clients/jedis/resps/StreamConsumersInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: enhancement

#3423 Add CLUSTER MYSHARDID command
  pom.xml
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/ClusterCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterCommandsTest.java
Labels: enhancement, dependencies, testing

#3425 Fix return value of HRANDFIELD With Values when count is negative
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/HashBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/HashCommands.java
  src/main/java/redis/clients/jedis/commands/HashPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/HashPipelineCommands.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/commands/jedis/HashesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/HashesCommandsTestBase.java
Labels: bug, breakingchange

#3430 Polishing #3425 and some tests
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/HashesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/AllKindOfValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/HashesCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
  src/test/java/redis/clients/jedis/util/AssertUtil.java
Labels: testing, documentation

#3436 Undo some of Jedis 5 breaking changes
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/main/java/redis/clients/jedis/resps/StreamConsumersInfo.java
  src/main/java/redis/clients/jedis/search/IndexDefinition.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: breakingchange

#3434 Use Keyword(s) in params classes
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/args/RawableFactory.java
  src/main/java/redis/clients/jedis/params/BitPosParams.java
  src/main/java/redis/clients/jedis/params/ClientKillParams.java
  src/main/java/redis/clients/jedis/params/CommandListFilterByParams.java
  src/main/java/redis/clients/jedis/params/FailoverParams.java
  src/main/java/redis/clients/jedis/params/GeoAddParams.java
  src/main/java/redis/clients/jedis/params/GeoRadiusParam.java
  src/main/java/redis/clients/jedis/params/GeoRadiusStoreParam.java
  src/main/java/redis/clients/jedis/params/GeoSearchParam.java
  src/main/java/redis/clients/jedis/params/GetExParams.java
  src/main/java/redis/clients/jedis/params/LCSParams.java
  src/main/java/redis/clients/jedis/params/LPosParams.java
  src/main/java/redis/clients/jedis/params/LolwutParams.java
  src/main/java/redis/clients/jedis/params/MigrateParams.java
  src/main/java/redis/clients/jedis/params/ModuleLoadExParams.java
  src/main/java/redis/clients/jedis/params/Params.java
  src/main/java/redis/clients/jedis/params/RestoreParams.java
  src/main/java/redis/clients/jedis/params/ScanParams.java
  src/main/java/redis/clients/jedis/params/SetParams.java
  src/main/java/redis/clients/jedis/params/ShutdownParams.java
  src/main/java/redis/clients/jedis/params/SortingParams.java
  src/main/java/redis/clients/jedis/params/XAddParams.java
  src/main/java/redis/clients/jedis/params/XAutoClaimParams.java
  src/main/java/redis/clients/jedis/params/XClaimParams.java
  src/main/java/redis/clients/jedis/params/XPendingParams.java
  src/main/java/redis/clients/jedis/params/XReadGroupParams.java
  src/main/java/redis/clients/jedis/params/XReadParams.java
  src/main/java/redis/clients/jedis/params/XTrimParams.java
  src/main/java/redis/clients/jedis/params/ZAddParams.java
  src/main/java/redis/clients/jedis/params/ZIncrByParams.java
  src/main/java/redis/clients/jedis/params/ZParams.java
  src/main/java/redis/clients/jedis/params/ZRangeParams.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/BinaryValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/FailoverCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/BinaryValuesCommandsTestBase.java
  src/test/java/redis/clients/jedis/misc/ParamsTest.java
  src/test/java/redis/clients/jedis/misc/ResponsesToStringTest.java
  src/test/java/redis/clients/jedis/misc/TupleTest.java
  src/test/java/redis/clients/jedis/params/ParamsTest.java
Labels: testing, breakingchange, maintenance

#3439 Modify BZPOP[MAX/MIN] return types
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineCommands.java
  src/main/java/redis/clients/jedis/resps/KeyedZSetElement.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
  src/test/java/redis/clients/jedis/misc/ResponsesToStringTest.java
Labels: breakingchange, maintenance

#3440 Modify B[L/R]POP return types
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/ListBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/ListCommands.java
  src/main/java/redis/clients/jedis/commands/ListPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/ListPipelineCommands.java
  src/main/java/redis/clients/jedis/resps/KeyedListElement.java
  src/test/java/redis/clients/jedis/commands/jedis/ListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/ListCommandsTestBase.java
  src/test/java/redis/clients/jedis/misc/ResponsesToStringTest.java
Labels: breakingchange, maintenance

#3310 Cross cluster failover
  README.md
  docs/failover.md
  pom.xml
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/exceptions/JedisValidationException.java
  src/main/java/redis/clients/jedis/executors/CircuitBreakerCommandExecutor.java
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
  src/test/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProviderTest.java
Labels: experimental

#3442 Polish 'pipelined()' in UnifiedJedis
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
Labels: enhancement

#3429 Support JSON.MERGE Command
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/json/JsonProtocol.java
  src/main/java/redis/clients/jedis/json/RedisJsonCommands.java
  src/main/java/redis/clients/jedis/json/RedisJsonPipelineCommands.java
  src/test/java/redis/clients/jedis/modules/json/JsonObjects.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV1Test.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV2Test.java
Labels: experimental

#3446 Add sleep after 'make start'
  .github/workflows/integration.yml
Labels: testing

#3443 Modify SentinelCommandsTest
  src/test/java/redis/clients/jedis/commands/jedis/SentinelCommandsTest.java
Labels: testing

#3431 Return List instead of Set in ZDIFF, ZINTER, ZUNION
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/SetPipelineCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineCommands.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
Labels: ready to merge, breakingchange, maintenance

#3444 'double' timeout parameter for BLMPOP and BZMPOP
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/ListBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/ListCommands.java
  src/main/java/redis/clients/jedis/commands/ListPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/ListPipelineCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineCommands.java
Labels: enhancement, breakingchange
