Repository redis/jedis, pull requests merged in 2023-03, with the labels that each got.

#3319 Abstraction for JSON object mapper
  pom.xml
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/GsonJson.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/json/DefaultGsonObjectMapper.java
  src/main/java/redis/clients/jedis/json/JsonObjectMapper.java
  src/test/java/redis/clients/jedis/modules/json/JsonObjects.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV1Test.java
  src/test/java/redis/clients/jedis/util/JsonObjectMapperTestUtil.java
Labels: experimental

#3321 Fixing codeql
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#3328 Test: More UDS test
  src/test/java/redis/clients/jedis/UdsTest.java
Labels: testing

#3329 Support parsing '-nan'
  src/main/java/redis/clients/jedis/util/DoublePrecision.java
  src/test/java/redis/clients/jedis/modules/graph/GraphValuesTest.java
Labels: backport required, maintenance

#3330 Improve safety of MultiNodePipelineBase under multi-thread
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
Labels: backport required, maintenance

#3331 Obtain multiple pipelines concurrently. high performance improvement
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
Labels: ready to merge

#3335 Address redis/redis#11942 and use MatcherAssert#assertThat
  src/main/java/redis/clients/jedis/resps/Tuple.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
  src/test/java/redis/clients/jedis/PipeliningTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AccessControlListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ObjectCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/modules/search/SchemaTest.java
  src/test/java/redis/clients/jedis/modules/search/SpellCheckTest.java
  src/test/java/redis/clients/jedis/params/ParamsTest.java
  src/test/java/redis/clients/jedis/resps/ResponsesToStringTest.java
  src/test/java/redis/clients/jedis/resps/TupleTest.java
Labels: testing

#3337 Fix error for javadoc plugin
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
Labels: documentation

#3336 Adding javadoc generation to CI
  .github/workflows/integration.yml
Labels: maintenance
