Repository redis/jedis, pull requests merged in 2023-06, with the labels that each got.

#3417 Modify TimeSeries commands after RESP3 update
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/timeseries/AggregationType.java
  src/main/java/redis/clients/jedis/timeseries/RedisTimeSeriesCommands.java
  src/main/java/redis/clients/jedis/timeseries/RedisTimeSeriesPipelineCommands.java
  src/main/java/redis/clients/jedis/timeseries/TSInfo.java
  src/main/java/redis/clients/jedis/timeseries/TSKeyValue.java
  src/main/java/redis/clients/jedis/timeseries/TSKeyedElements.java
  src/main/java/redis/clients/jedis/timeseries/TSMGetElement.java
  src/main/java/redis/clients/jedis/timeseries/TSMRangeElements.java
  src/main/java/redis/clients/jedis/timeseries/TimeSeriesBuilderFactory.java
  src/test/java/redis/clients/jedis/modules/RedisModuleCommandsTestBase.java
  src/test/java/redis/clients/jedis/modules/timeseries/TimeSeriesTest.java
  src/test/java/redis/clients/jedis/util/AssertUtil.java
Labels: breakingchange, experimental

#3451 Refactor Search Aggregation codes
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/search/FTSearchParams.java
  src/main/java/redis/clients/jedis/search/FieldName.java
  src/main/java/redis/clients/jedis/search/Query.java
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationBuilder.java
  src/main/java/redis/clients/jedis/search/aggr/Group.java
  src/main/java/redis/clients/jedis/search/aggr/Limit.java
  src/main/java/redis/clients/jedis/search/aggr/Reducer.java
  src/main/java/redis/clients/jedis/search/aggr/Reducers.java
  src/main/java/redis/clients/jedis/util/LazyRawable.java
Labels: breakingchange, experimental

#3453 Undo stream builder rename
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerInfo.java
  src/main/java/redis/clients/jedis/resps/StreamConsumersInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: maintenance

#3454 Add zdiffstore
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterSortedSetCommandsTest.java
Labels: maintenance

#3449 Client setinfo ignore all exception
  src/main/java/redis/clients/jedis/Connection.java
  src/test/java/redis/clients/jedis/JedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPooledTest.java
Labels: backport required, bug

#3455 Add an option to ignore cluster init error
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
  src/test/java/redis/clients/jedis/misc/ClusterInitErrorTest.java
Labels: backport required, maintenance, docs-review

#3458 Client setinfo ignore all exception (#3449)
  src/main/java/redis/clients/jedis/Connection.java
  src/test/java/redis/clients/jedis/JedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPooledTest.java
Labels: bug

#3452 Allow setting default dialect for search module
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/FTSearchParams.java
  src/main/java/redis/clients/jedis/search/FTSpellCheckParams.java
  src/main/java/redis/clients/jedis/search/Query.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationBuilder.java
  src/main/java/redis/clients/jedis/search/aggr/FtAggregateIteration.java
  src/test/java/redis/clients/jedis/modules/search/SearchDefaultDialectTest.java
Labels: ready to merge, breakingchange, experimental

#3461 Fix tsInfoDebug after update
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/timeseries/TSInfo.java
Labels: maintenance, experimental

#3456 Use List<KeyValue> to read RESP3 Map reply
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Module.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/commands/AccessControlLogBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/AccessControlLogCommands.java
  src/main/java/redis/clients/jedis/commands/ConfigCommands.java
  src/main/java/redis/clients/jedis/resps/AccessControlLogEntry.java
  src/main/java/redis/clients/jedis/resps/AccessControlUser.java
  src/main/java/redis/clients/jedis/resps/CommandDocument.java
  src/main/java/redis/clients/jedis/resps/FunctionStats.java
  src/main/java/redis/clients/jedis/resps/LibraryInfo.java
  src/main/java/redis/clients/jedis/resps/Slowlog.java
  src/main/java/redis/clients/jedis/timeseries/TSInfo.java
  src/main/java/redis/clients/jedis/timeseries/TimeSeriesBuilderFactory.java
  src/main/java/redis/clients/jedis/util/SafeEncoder.java
  src/test/java/redis/clients/jedis/JedisTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AccessControlListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/AllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/JedisCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/jedis/ModuleTest.java
  src/test/java/redis/clients/jedis/commands/jedis/ScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SlowlogCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/AllKindOfValuesCommandsTestBase.java
Labels: breakingchange, maintenance

#3467 Shutdown ExecutorService(s) in multi node pipelines
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
Labels: ready to merge, bug
