Repository redis/jedis, pull requests merged in 2023-10, with the labels that each got.

#3573 Bump junixsocket-core to 2.8.1
  pom.xml
Labels: dependencies, testing

#3561 Support GEOSHAPE field type in RediSearch
  pom.xml
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/main/java/redis/clients/jedis/search/schemafields/GeoShapeField.java
  src/test/java/redis/clients/jedis/examples/GeoShapeFieldsUsageInRediSearch.java
  src/test/java/redis/clients/jedis/modules/search/QueryBuilderTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental

#3571 Fix binary variants of XRANGE and XREAD commands
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StreamBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineBinaryCommands.java
Labels: ready to merge, backport required, bug

#3576 Allow getting schema field name
  src/main/java/redis/clients/jedis/search/FieldName.java
  src/main/java/redis/clients/jedis/search/schemafields/SchemaField.java
  src/test/java/redis/clients/jedis/modules/search/UtilTest.java
Labels: backport required, maintenance

#3578 Release minor version snapshots
  .github/workflows/integration.yml
  .github/workflows/snapshot.yml
Labels: maintenance

#3580 Backport changes in workflows
  .github/workflows/integration.yml
  .github/workflows/snapshot.yml
Labels: maintenance

#3583 Linking to Redis learning resources
  README.md
Labels: maintenance

#3584 Fix SORTABLE argument issue in FT.CREATE command
  src/main/java/redis/clients/jedis/search/schemafields/TagField.java
  src/main/java/redis/clients/jedis/search/schemafields/TextField.java
Labels: backport required, experimental

#3587 Use simple version of HSET
  src/test/java/redis/clients/jedis/examples/GeoShapeFieldsUsageInRediSearch.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: testing, documentation, docs-review

#3589 Move pom.properties file into redis.clients.jedis package
  src/main/java/redis/clients/jedis/util/JedisMetaInfo.java
  src/main/resources/redis/clients/jedis/pom.properties
Labels: backport required, maintenance

#3590 Move JedisMetaInfo into parent package and make it package private
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/JedisMetaInfo.java
  src/test/java/redis/clients/jedis/JedisTest.java
Labels: backport required, breakingchange

#3591 Warning about JedisMetaInfo movement
  src/main/java/redis/clients/jedis/util/JedisMetaInfo.java
Labels: maintenance

#3593 Direct FT.CREATE to proper node in LIGHT search mode
  src/main/java/redis/clients/jedis/CommandObjects.java
Labels: bug
