Repository redis/jedis, pull requests merged in 2023-12, with the labels that each got.

#3656 Bump maven-surefire-plugin to 3.2.3
  pom.xml
Labels: dependencies

#3658 Initial support for client-side caching
  src/main/java/redis/clients/jedis/ClientSideCache.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/JedisClientSideCache.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/util/RedisInputStream.java
  src/test/java/redis/clients/jedis/JedisClientSideCacheTest.java
Labels: feature, experimental

#3670 Fixing GPG key usage
  .github/workflows/version-and-release.yml
Labels: maintenance

#3660 Java example code snippets for T-Digest and TopK
  src/test/java/io/redis/examples/TDigestExample.java
  src/test/java/io/redis/examples/TopKExample.java
Labels: docs-review

#3622 Replace deprecated set-output command with environment file
  .github/workflows/version-and-release.yml
Labels: maintenance
