Repository redis/jedis, pull requests merged in 2023-08, with the labels that each got.

#3487 Add Geospatial data type example
  src/test/java/io/redis/examples/GeoExample.java
Labels: documentation, docs-review

#3495 Support TOPK.LIST with WITHCOUNT option
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/bloom/RedisBloomProtocol.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterCommands.java
  src/main/java/redis/clients/jedis/bloom/commands/TopKFilterPipelineCommands.java
  src/test/java/redis/clients/jedis/modules/bloom/TopKTest.java
Labels: backport required, experimental

#3486 Fixed some typos and formatting issues across the project
  README.md
  src/main/java/redis/clients/jedis/StreamEntryID.java
  src/main/java/redis/clients/jedis/commands/ServerCommands.java
  src/main/java/redis/clients/jedis/params/MigrateParams.java
  src/main/java/redis/clients/jedis/params/ZAddParams.java
  src/main/java/redis/clients/jedis/resps/AccessControlLogEntry.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamConsumerInfo.java
  src/main/java/redis/clients/jedis/resps/StreamConsumersInfo.java
  src/main/java/redis/clients/jedis/resps/StreamFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamGroupFullInfo.java
  src/main/java/redis/clients/jedis/resps/StreamGroupInfo.java
  src/main/java/redis/clients/jedis/resps/StreamInfo.java
  src/main/java/redis/clients/jedis/util/RedisInputStream.java
  src/test/java/redis/clients/jedis/ConnectionTest.java
Labels: documentation

#3478 Compatible JDK for JEDIS libraries in README (minor)
  README.md
Labels: maintenance

#3496 Updating client license to clear, MIT
  LICENSE
  LICENSE.txt
Labels: maintenance

#3497 Fixed few typos and grammar issues across the project
  README.md
  docs/failover.md
  pom.xml
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/commands/ClientBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/ClientCommands.java
  src/main/java/redis/clients/jedis/commands/ClusterCommands.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/main/java/redis/clients/jedis/commands/StringCommands.java
  src/main/java/redis/clients/jedis/graph/Record.java
  src/main/java/redis/clients/jedis/graph/ResultSetBuilder.java
  src/main/java/redis/clients/jedis/search/querybuilder/Node.java
  src/test/java/redis/clients/jedis/ACLJedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPoolTest.java
Labels: documentation

#3464 Support Search commands after RESP3 update
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/search/Document.java
  src/main/java/redis/clients/jedis/search/FtSearchIteration.java
  src/main/java/redis/clients/jedis/search/RediSearchCommands.java
  src/main/java/redis/clients/jedis/search/RediSearchPipelineCommands.java
  src/main/java/redis/clients/jedis/search/SearchBuilderFactory.java
  src/main/java/redis/clients/jedis/search/SearchResult.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationResult.java
  src/main/java/redis/clients/jedis/search/aggr/FtAggregateIteration.java
  src/test/java/redis/clients/jedis/modules/RedisModulesPipelineTest.java
  src/test/java/redis/clients/jedis/modules/json/JsonObjects.java
  src/test/java/redis/clients/jedis/modules/search/AggregationTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchConfigTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
  src/test/java/redis/clients/jedis/modules/search/SpellCheckTest.java
Labels: breakingchange, experimental

#3460 Support Json commands after RESP3 update
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/PipelineBase.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/json/JsonBuilderFactory.java
  src/main/java/redis/clients/jedis/json/commands/RedisJsonV2Commands.java
  src/main/java/redis/clients/jedis/json/commands/RedisJsonV2PipelineCommands.java
  src/test/java/redis/clients/jedis/modules/RedisModulesPipelineTest.java
  src/test/java/redis/clients/jedis/modules/json/JsonObjects.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV1Test.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV2Test.java
Labels: experimental, docs-review

#3502 Remove JSON.RESP command support
  docs/jedis5-breaking.md
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/json/commands/RedisJsonV1Commands.java
  src/main/java/redis/clients/jedis/json/commands/RedisJsonV2Commands.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV1Test.java
  src/test/java/redis/clients/jedis/modules/json/RedisJsonV2Test.java
Labels: breakingchange, experimental

#3503 Deprecate RedisJSON v1 support
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/json/Path.java
  src/main/java/redis/clients/jedis/json/Path2.java
  src/main/java/redis/clients/jedis/json/commands/RedisJsonV1Commands.java
  src/main/java/redis/clients/jedis/json/commands/RedisJsonV1PipelineCommands.java
Labels: maintenance

#3506 Fix flakyness of JedisPooledTest
  src/test/java/redis/clients/jedis/JedisPooledTest.java
Labels: testing

#3507 Use RedisCredentials with HELLO command
  src/main/java/redis/clients/jedis/Connection.java
Labels: enhancement

#3510 Deprecate more items that will be removed in Jedis 5
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Queable.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/json/RedisJsonCommands.java
  src/main/java/redis/clients/jedis/params/Params.java
  src/main/java/redis/clients/jedis/params/SortingParams.java
  src/main/java/redis/clients/jedis/params/StrAlgoLCSParams.java
  src/main/java/redis/clients/jedis/resps/KeyedListElement.java
  src/main/java/redis/clients/jedis/resps/KeyedZSetElement.java
  src/main/java/redis/clients/jedis/search/Document.java
  src/main/java/redis/clients/jedis/search/FieldName.java
  src/main/java/redis/clients/jedis/search/IndexDefinition.java
  src/main/java/redis/clients/jedis/search/Query.java
  src/main/java/redis/clients/jedis/search/SearchResult.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationBuilder.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationResult.java
  src/main/java/redis/clients/jedis/search/aggr/Group.java
  src/main/java/redis/clients/jedis/search/aggr/Limit.java
  src/main/java/redis/clients/jedis/timeseries/TSKeyValue.java
  src/main/java/redis/clients/jedis/timeseries/TSKeyedElements.java
Labels: maintenance

#3514 Remove unused AbortedTransactionException
  docs/breaking-5.md
  src/main/java/redis/clients/jedis/exceptions/AbortedTransactionException.java
  src/test/java/redis/clients/jedis/exceptions/ExceptionsTest.java
Labels: breakingchange, maintenance

#3517 Type-cast the Pipeline object in JedisSentineled
  src/main/java/redis/clients/jedis/JedisSentineled.java
Labels: enhancement

#3518 Modify JedisBroadcastException
  src/main/java/redis/clients/jedis/exceptions/JedisBroadcastException.java
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
  src/test/java/redis/clients/jedis/commands/jedis/ClusterScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledMiscellaneousTest.java
Labels: backport required, breakingchange, maintenance
