Repository redis/jedis, pull requests merged in 2024-11, with the labels that each got.

#4010 DOC-4345 added JSON search examples for home page
  src/test/java/io/redis/examples/HomeJsonExample.java
Labels: docs-review

#4022 COMMAND INFO reply contains subcommand detail
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/resps/CommandInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
Labels: backport required, bug, breakingchange

#4024 Add examples and tutorials page
  .github/wordlist.txt
  docs/tutorials_examples.md
  mkdocs.yml
Labels: docs-review

#4026 Implement command (no arg)
  src/main/java/redis/clients/jedis/Jedis.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
Labels: enhancement

#4030 Make reply of ACL LOG compatible with older Redis versions
  src/main/java/redis/clients/jedis/resps/AccessControlLogEntry.java
Labels: maintenance

#4031 Make reply of COMMAND INFO compatible with older Redis versions
  src/main/java/redis/clients/jedis/resps/CommandInfo.java
Labels: maintenance
