Repository redis/jedis, pull requests merged in 2024-02, with the labels that each got.

#3700 Client-side caching by hashing command arguments
  pom.xml
  src/main/java/redis/clients/jedis/ClientSideCache.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/util/CaffeineCSC.java
  src/main/java/redis/clients/jedis/util/GuavaCSC.java
  src/test/java/redis/clients/jedis/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/JedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/util/MapCSC.java
Labels: experimental

#3703 Support Client-side caching through URI/URL
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/util/JedisURIHelper.java
Labels: experimental

#3726 Check for thread interrupt in subscribe process of PubSub
  src/main/java/redis/clients/jedis/JedisPubSubBase.java
  src/main/java/redis/clients/jedis/JedisShardedPubSubBase.java
  src/test/java/redis/clients/jedis/JedisPubSubBaseTest.java
  src/test/java/redis/clients/jedis/JedisShardedPubSubBaseTest.java
Labels: backport required, bug

#3729 Support issuing Latency commands
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/args/LatencyEvent.java
  src/main/java/redis/clients/jedis/commands/ServerCommands.java
  src/main/java/redis/clients/jedis/resps/LatencyHistoryInfo.java
  src/main/java/redis/clients/jedis/resps/LatencyLatestInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/ControlCommandsTest.java
Labels: enhancement

#3741 Add support for the NOVALUES option of HSCAN
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/HashBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/HashCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/HashesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/HashesCommandsTestBase.java
Labels: feature

#3742 Test GuavaCSC and CaffeineCSC
  src/main/java/redis/clients/jedis/util/GuavaCSC.java
  src/test/java/redis/clients/jedis/ClientSideCacheLibsTest.java
Labels: experimental

#3746 Polish #3741
  src/main/java/redis/clients/jedis/PipeliningBase.java
  src/main/java/redis/clients/jedis/commands/HashBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/HashCommands.java
  src/main/java/redis/clients/jedis/commands/HashPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/HashPipelineCommands.java
Labels: feature

#3750 Reduce the log level of validateObject to WARN
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/JedisFactory.java
Labels: breakingchange, maintenance
