Repository redis/jedis, pull requests merged in 2024-07, with the labels that each got.

#3881 [TEMPORARY] [TEST] Disable FT.PROFILE tests
  src/test/java/redis/clients/jedis/modules/search/AggregationTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: testing

#3882 Inject ClientSideCacheable via set method
  src/main/java/redis/clients/jedis/csc/CaffeineClientSideCache.java
  src/main/java/redis/clients/jedis/csc/ClientSideCache.java
  src/main/java/redis/clients/jedis/csc/GuavaClientSideCache.java
  src/test/java/redis/clients/jedis/csc/AllowAndDenyListClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/MapClientSideCache.java
Labels: experimental

#3875 Use CommandObject(s) as cache-key
  pom.xml
  src/main/java/redis/clients/jedis/CommandObject.java
  src/main/java/redis/clients/jedis/args/Rawable.java
  src/main/java/redis/clients/jedis/args/RawableFactory.java
  src/main/java/redis/clients/jedis/csc/CaffeineClientSideCache.java
  src/main/java/redis/clients/jedis/csc/ClientSideCache.java
  src/main/java/redis/clients/jedis/csc/GuavaClientSideCache.java
  src/main/java/redis/clients/jedis/csc/hash/AbstractCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/AbstractSimpleCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/CommandLongHasher.java
  src/main/java/redis/clients/jedis/csc/hash/GuavaCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/SimpleCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/package-info.java
  src/test/java/redis/clients/jedis/csc/AllowAndDenyListClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/CaffeineClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/GuavaClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/MapClientSideCache.java
  src/test/java/redis/clients/jedis/csc/OpenHftCommandHasher.java
Labels: experimental

#3883 Use Redis 7.4 branch and 7.4.0-rc2 image for testing
  .github/workflows/integration.yml
  Makefile
Labels: testing

#3886 Remove RediSearch DIALECT 5 support
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: testing, experimental

#3892 Remove client side cache support through uri/url
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/util/JedisURIHelper.java
  src/test/java/redis/clients/jedis/csc/CaffeineClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/GuavaClientSideCacheTest.java
Labels: experimental

#3887 Extract messages of unsupported exception as constants
  src/main/java/redis/clients/jedis/mcf/MultiClusterTransaction.java
Labels: maintenance

#3480 Replace `synchronized` with `j.u.c.l.ReentrantLock` for Loom
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/JedisSentinelPool.java
  src/main/java/redis/clients/jedis/graph/GraphCommandObjects.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverBase.java
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
  src/main/java/redis/clients/jedis/providers/SentineledConnectionProvider.java
Labels: maintenance

#3888 Modify the judgment that reads a response as empty to isEmpty method.
  src/main/java/redis/clients/jedis/util/RedisInputStream.java
Labels: maintenance

#3896 JedisConnectionException contains HostAndPort from DefaultJedisSocketFactory
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
Labels: enhancement, breakingchange

#3889 Prepare client side caching - design 2
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/csc/CacheConnection.java
  src/main/java/redis/clients/jedis/csc/CacheEntry.java
  src/main/java/redis/clients/jedis/csc/CacheKey.java
  src/main/java/redis/clients/jedis/csc/CaffeineClientSideCache.java
  src/main/java/redis/clients/jedis/csc/ClientSideCache.java
  src/main/java/redis/clients/jedis/csc/GuavaClientSideCache.java
  src/main/java/redis/clients/jedis/providers/SentineledConnectionProvider.java
  src/test/java/redis/clients/jedis/commands/jedis/TransactionCommandsTest.java
  src/test/java/redis/clients/jedis/csc/AllowAndDenyListClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/MapClientSideCache.java
Labels: experimental

#3907 [TEMPORARY] [TEST] Disable FT.CONFIG tests
  src/test/java/redis/clients/jedis/modules/RedisModulesPipelineTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchConfigTest.java
Labels: testing

#3908 Added support for ADDSCORES argument in FT.AGGREGATE
  src/main/java/redis/clients/jedis/search/SearchProtocol.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationBuilder.java
  src/test/java/redis/clients/jedis/modules/search/AggregationTest.java
Labels: experimental

#3911 Use Redis 7.4 branch and 7.4.0-v0 image for testing
  .github/workflows/integration.yml
Labels: testing
