Repository redis/jedis, pull requests merged in 2024-01, with the labels that each got.

#3650 Unifying GitHub tokens
  .github/workflows/version-and-release.yml
Labels: maintenance

#3570 Creating CODEOWNERS for documentation
  .github/CODEOWNERS
Labels: maintenance

#3528 Adding stale issues workflow
  .github/workflows/stale-issues.yml
Labels: maintenance

#3492 Spellcheck as part of CI
  .github/spellcheck-settings.yml
  .github/wordlist.txt
  .github/workflows/spellcheck.yml
Labels: maintenance

#3661 Create Java code snippets for sets redis#3626
  src/test/java/io/redis/examples/SetsExample.java
Labels: docs-review

#3664 Use circuit breaker fallback exception list
  .github/wordlist.txt
  docs/failover.md
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverBase.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverConnectionProvider.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterPipeline.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterTransaction.java
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
  src/test/java/redis/clients/jedis/misc/AutomaticFailoverTest.java
Labels: bug

#3673 Support for client-side caching - phase 2
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/JedisClientSideCache.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/util/RedisInputStream.java
  src/test/java/redis/clients/jedis/JedisClientSideCacheTest.java
Labels: experimental

#3681 Run integration workflow for 5.2.0 branch
  .github/workflows/integration.yml
Labels: testing

#3644 Create Java code snippets for count min sketch
  src/test/java/io/redis/examples/CMSExample.java
Labels: docs-review

#3671 Added Java code snippets for Bloom #3630
  src/test/java/io/redis/examples/BloomFilterExample.java
Labels: docs-review

#3674 Added java code snippet for hyperloglog
  src/test/java/io/redis/examples/HyperLogLogExample.java
Labels: docs-review

#3679 Added Java code snippets for cuckoo filters
  src/test/java/io/redis/examples/CuckooFilterExample.java
Labels: docs-review

#3677 Create Java code snippet for lists #3625
  src/test/java/io/redis/examples/ListExample.java
Labels: docs-review

#3680 Create Java code snippet for sorted sets
  src/test/java/io/redis/examples/SortedSetsExample.java
Labels: docs-review

#3692 Fix probable missing (RESP3) protocol processing
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/JedisSentineled.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
Labels: bug

#3693 Running doctests also on emb-examples
  .github/workflows/doctests.yml
Labels: maintenance

#3691 Support client-side caching from UnifiedJedis
  src/main/java/redis/clients/jedis/ClientSideCache.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/ConnectionPool.java
  src/main/java/redis/clients/jedis/JedisClientSideCache.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/JedisSentineled.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
  src/main/java/redis/clients/jedis/providers/PooledConnectionProvider.java
  src/main/java/redis/clients/jedis/providers/SentineledConnectionProvider.java
  src/test/java/redis/clients/jedis/JedisClientSideCacheTest.java
  src/test/java/redis/clients/jedis/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/JedisClusterTest.java
  src/test/java/redis/clients/jedis/JedisClusterTestBase.java
  src/test/java/redis/clients/jedis/JedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/SentineledConnectionProviderTest.java
Labels: experimental

#3697 Avoid NPE in MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
Labels: backport required, bug
