Repository redis/jedis, pull requests merged in 2024-09, with the labels that each got.

#3944 DOC-4080 Sorted Set (ZADD and ZRANGE commands) examples
  src/test/java/io/redis/examples/CmdsSortedSetExample.java
Labels: docs-review

#3935 Add A-A failover scenario test
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
  src/test/java/redis/clients/jedis/EndpointConfig.java
  src/test/java/redis/clients/jedis/scenario/ActiveActiveFailoverTest.java
  src/test/java/redis/clients/jedis/scenario/FakeApp.java
  src/test/java/redis/clients/jedis/scenario/MultiThreadedFakeApp.java
Labels: testing

#3954 Server version check for CSC activation
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/csc/AbstractCache.java
  src/main/java/redis/clients/jedis/csc/Cache.java
  src/main/java/redis/clients/jedis/csc/CacheConnection.java
  src/main/java/redis/clients/jedis/csc/RedisVersion.java
  src/test/java/redis/clients/jedis/csc/VersionTest.java
Labels: experimental

#3945 DOC-4082 code examples for DEL, EXPIRE, and TTL
  src/test/java/io/redis/examples/CmdsGenericExample.java
Labels: docs-review

#3946 DOC-4102 INCR command example
  src/test/java/io/redis/examples/CmdsStringExample.java
Labels: docs-review

#3304 Added JavaDoc for basic JedisCluster constructors
  src/main/java/redis/clients/jedis/JedisCluster.java
Labels: documentation

#3959 Add equals and hashCode to Timeseries Params classes
  src/main/java/redis/clients/jedis/timeseries/TSAddParams.java
  src/main/java/redis/clients/jedis/timeseries/TSAlterParams.java
  src/main/java/redis/clients/jedis/timeseries/TSArithByParams.java
  src/main/java/redis/clients/jedis/timeseries/TSCreateParams.java
  src/main/java/redis/clients/jedis/timeseries/TSGetParams.java
  src/main/java/redis/clients/jedis/timeseries/TSMGetParams.java
  src/main/java/redis/clients/jedis/timeseries/TSMRangeParams.java
  src/main/java/redis/clients/jedis/timeseries/TSRangeParams.java
Labels: enhancement

#3963 DOC-4252 full-text examples
  src/test/java/io/redis/examples/QueryFtExample.java
Labels: docs-review

#3964 DOC-4202 exact match search examples
  src/test/java/io/redis/examples/QueryEmExample.java
Labels: docs-review

#3967 DOC-4296 added aggregation query examples
  src/test/java/io/redis/examples/QueryAggExample.java
Labels: docs-review

#3965 DOC-4244 added range query examples
  src/test/java/io/redis/examples/QueryRangeExample.java
Labels: docs-review

#3968 Deprecate Triggers and Functions feature
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/gears/RedisGearsCommands.java
  src/main/java/redis/clients/jedis/gears/RedisGearsProtocol.java
  src/main/java/redis/clients/jedis/gears/TFunctionListParams.java
  src/main/java/redis/clients/jedis/gears/TFunctionLoadParams.java
  src/main/java/redis/clients/jedis/gears/resps/FunctionInfo.java
  src/main/java/redis/clients/jedis/gears/resps/FunctionStreamInfo.java
  src/main/java/redis/clients/jedis/gears/resps/GearsLibraryInfo.java
  src/main/java/redis/clients/jedis/gears/resps/StreamTriggerInfo.java
  src/main/java/redis/clients/jedis/gears/resps/TriggerInfo.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsTriggersAndFunctionsCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisTriggersAndFunctionsCommandsTest.java
  src/test/java/redis/clients/jedis/modules/gears/GearsTest.java
Labels: backport required, experimental

#3757 Support Server-assisted Client-side Caching
  pom.xml
  src/main/java/redis/clients/jedis/CommandArguments.java
  src/main/java/redis/clients/jedis/CommandObject.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/ConnectionPool.java
  src/main/java/redis/clients/jedis/DefaultJedisSocketFactory.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisFactory.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/JedisSentineled.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/SSLSocketWrapper.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/annots/Experimental.java
  src/main/java/redis/clients/jedis/args/Rawable.java
  src/main/java/redis/clients/jedis/args/RawableFactory.java
  src/main/java/redis/clients/jedis/csc/AbstractCache.java
  src/main/java/redis/clients/jedis/csc/Cache.java
  src/main/java/redis/clients/jedis/csc/CacheConfig.java
  src/main/java/redis/clients/jedis/csc/CacheConnection.java
  src/main/java/redis/clients/jedis/csc/CacheEntry.java
  src/main/java/redis/clients/jedis/csc/CacheFactory.java
  src/main/java/redis/clients/jedis/csc/CacheKey.java
  src/main/java/redis/clients/jedis/csc/CacheStats.java
  src/main/java/redis/clients/jedis/csc/Cacheable.java
  src/main/java/redis/clients/jedis/csc/DefaultCache.java
  src/main/java/redis/clients/jedis/csc/DefaultCacheable.java
  src/main/java/redis/clients/jedis/csc/EvictionPolicy.java
  src/main/java/redis/clients/jedis/csc/LRUEviction.java
  src/main/java/redis/clients/jedis/csc/RedisVersion.java
  src/main/java/redis/clients/jedis/csc/package-info.java
  src/main/java/redis/clients/jedis/csc/util/AllowAndDenyListWithStringKeys.java
  src/main/java/redis/clients/jedis/csc/util/package-info.java
  src/main/java/redis/clients/jedis/exceptions/JedisCacheException.java
  src/main/java/redis/clients/jedis/mcf/package-info.java
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
  src/main/java/redis/clients/jedis/providers/PooledConnectionProvider.java
  src/main/java/redis/clients/jedis/providers/SentineledConnectionProvider.java
  src/main/java/redis/clients/jedis/util/JedisURIHelper.java
  src/main/java/redis/clients/jedis/util/RedisInputStream.java
  src/test/java/redis/clients/jedis/JedisClusterTest.java
  src/test/java/redis/clients/jedis/JedisClusterTestBase.java
  src/test/java/redis/clients/jedis/SSLJedisTest.java
  src/test/java/redis/clients/jedis/benchmark/CSCPooleadBenchmark.java
  src/test/java/redis/clients/jedis/commands/jedis/TransactionCommandsTest.java
  src/test/java/redis/clients/jedis/csc/AllowAndDenyListCacheableTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/SSLJedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/TestCache.java
  src/test/java/redis/clients/jedis/csc/UnifiedJedisClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/csc/VersionTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: experimental
