Repository redis/jedis, pull requests merged in 2024-08, with the labels that each got.

#3917 Fixed typo in Javadoc
  src/main/java/redis/clients/jedis/Jedis.java
Labels: documentation

#3745 Get enriched Connection information
  src/main/java/redis/clients/jedis/Connection.java
  src/test/java/redis/clients/jedis/ConnectionTest.java
Labels: enhancement

#3918 Jedis test plan coverage for CSC
  pom.xml
  src/main/java/redis/clients/jedis/CommandArguments.java
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/csc/AbstractCache.java
  src/main/java/redis/clients/jedis/csc/Cache.java
  src/main/java/redis/clients/jedis/csc/CacheConnection.java
  src/main/java/redis/clients/jedis/csc/CacheEntry.java
  src/main/java/redis/clients/jedis/csc/CacheKey.java
  src/main/java/redis/clients/jedis/csc/Cacheable.java
  src/main/java/redis/clients/jedis/csc/CaffeineClientSideCache.java
  src/main/java/redis/clients/jedis/csc/ClientSideCacheable.java
  src/main/java/redis/clients/jedis/csc/DefaultCache.java
  src/main/java/redis/clients/jedis/csc/DefaultCacheable.java
  src/main/java/redis/clients/jedis/csc/DefaultClientSideCacheable.java
  src/main/java/redis/clients/jedis/csc/GuavaClientSideCache.java
  src/main/java/redis/clients/jedis/csc/util/AllowAndDenyListWithStringKeys.java
  src/main/java/redis/clients/jedis/exceptions/JedisCacheException.java
  src/test/java/redis/clients/jedis/SSLJedisTest.java
  src/test/java/redis/clients/jedis/csc/AllowAndDenyListCacheableTest.java
  src/test/java/redis/clients/jedis/csc/CaffeineClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/csc/GuavaClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/SSLJedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/TestCache.java
  src/test/java/redis/clients/jedis/csc/UnifiedJedisClientSideCacheTestBase.java
Labels: experimental

#3922 Use ExecutorService.shutdownNow() in tests
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
Labels: testing

#3924 Fix empty LUA table reply
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/test/java/redis/clients/jedis/commands/jedis/ScriptingCommandsTest.java
Labels: backport required, bug

#3781 Support automatic namespacing
  src/main/java/redis/clients/jedis/AbstractTransaction.java
  src/main/java/redis/clients/jedis/ClusterCommandObjects.java
  src/main/java/redis/clients/jedis/CommandArguments.java
  src/main/java/redis/clients/jedis/CommandKeyArgumentPreProcessor.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/ReliableTransaction.java
  src/main/java/redis/clients/jedis/ShardedCommandObjects.java
  src/main/java/redis/clients/jedis/Transaction.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterTransaction.java
  src/main/java/redis/clients/jedis/util/PrefixedKeyArgumentPreProcessor.java
  src/test/java/redis/clients/jedis/prefix/JedisClusterPrefixedKeysTest.java
  src/test/java/redis/clients/jedis/prefix/JedisPooledPrefixedKeysTest.java
  src/test/java/redis/clients/jedis/prefix/JedisSentineledPrefixedKeysTest.java
  src/test/java/redis/clients/jedis/prefix/PrefixedKeysTest.java
Labels: experimental

#3897 Revert "Creating CODEOWNERS for the examples (#3570)"
  .github/CODEOWNERS
Labels: maintenance

#3931 Modify Connection.toIdentityString and test
  src/main/java/redis/clients/jedis/Connection.java
  src/test/java/redis/clients/jedis/ConnectionTest.java
Labels: maintenance

#3930 Accept null replies for BZPOPMAX and BZPOPMIN commands
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/test/java/redis/clients/jedis/commands/jedis/SortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/SortedSetCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterSortedSetCommandsTest.java
Labels: backport required, bug

#3932 Rename readonly config param to specify Redis Cluster
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/test/java/redis/clients/jedis/JedisClusterTest.java
Labels: maintenance

#3933 Fix codecov upload
  .github/workflows/integration.yml
Labels: maintenance

#3934 [DOC] RediSearch usage with FTCreateParams and FTSearchParams classes
  .github/wordlist.txt
  docs/redisearch.md
  docs/redisjson.md
Labels: docs-review

#3926 Decoding FT.SEARCH reply can be disabled at field level
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/search/Document.java
  src/main/java/redis/clients/jedis/search/FTSearchParams.java
  src/main/java/redis/clients/jedis/search/SearchResult.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: enhancement

#3939 Support caching null values
  src/main/java/redis/clients/jedis/csc/CacheConnection.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/UnifiedJedisClientSideCacheTestBase.java
Labels: experimental

#3919 Adding CacheConfig
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/JedisSentineled.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/csc/CacheConfig.java
  src/main/java/redis/clients/jedis/csc/CacheConnection.java
  src/main/java/redis/clients/jedis/csc/CacheProvider.java
  src/main/java/redis/clients/jedis/csc/DefaultCache.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/TestCache.java
  src/test/java/redis/clients/jedis/csc/UnifiedJedisClientSideCacheTestBase.java
Labels: experimental

#3940 DOC-4094 hash examples
  src/test/java/io/redis/examples/CmdsHashExample.java
Labels: docs-review

#3942 Adding Cache class to CacheConfig
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/JedisSentineled.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/csc/CacheConfig.java
  src/main/java/redis/clients/jedis/csc/CacheFactory.java
  src/main/java/redis/clients/jedis/csc/CacheProvider.java
  src/main/java/redis/clients/jedis/csc/DefaultCache.java
  src/test/java/redis/clients/jedis/csc/AllowAndDenyListCacheableTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheFunctionalityTest.java
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/TestCache.java
  src/test/java/redis/clients/jedis/csc/UnifiedJedisClientSideCacheTestBase.java
Labels: experimental
