Repository redis/jedis, pull requests merged in 2024-10, with the labels that each got.

#3975 Jedis 5.2.0 is released; bump snapshot version to 5.3.0
  README.md
  pom.xml
Labels: documentation, maintenance

#3984 DOC-4317 fixed flaky tests
  src/test/java/io/redis/examples/QueryAggExample.java
  src/test/java/io/redis/examples/QueryEmExample.java
  src/test/java/io/redis/examples/QueryFtExample.java
  src/test/java/io/redis/examples/QueryRangeExample.java
Labels: testing, docs-review

#3990 Fix JavaDoc warnings
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/DefaultJedisClientConfig.java
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/commands/FunctionBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/SortedSetPipelineBinaryCommands.java
Labels: backport required, documentation

#3991 Add javadoc to clear up implicit behavior
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
Labels: documentation

#3972 Fix flaky tests with 'await'
  pom.xml
  src/test/java/redis/clients/jedis/PipeliningTest.java
  src/test/java/redis/clients/jedis/csc/UnifiedJedisClientSideCacheTestBase.java
  src/test/java/redis/clients/jedis/util/AssertUtil.java
Labels: backport required, testing

#3996 Codecove has released beta version of Test Analytics feature
  .github/codecov.yml
  .github/workflows/integration.yml
Labels: maintenance

#3974 Update links in README
  README.md
Labels: documentation, docs-review

#3999 Mkdocs unify docs
  .github/spellcheck-settings.yml
  .github/wordlist.txt
  .github/workflows/docs.yml
  docs/Dockerfile
  docs/README.md
  docs/advanced-usage.md
  docs/assets/images/favicon-16x16.png
  docs/assets/images/logo.png
  docs/css/extra.css
  docs/faq.md
  docs/index.md
  mkdocs.yml
Labels: maintenance
