Repository redis/jedis, pull requests merged in 2024-03, with the labels that each got.

#3756 Stop connection fetching before sync/exec
  src/main/java/redis/clients/jedis/AbstractTransaction.java
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/TransactionBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterPipeline.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterTransaction.java
  src/test/java/redis/clients/jedis/misc/AutomaticFailoverTest.java
Labels: backport required, bug

#3743 Introduce interface(s) for hashing CommandObject
  src/main/java/redis/clients/jedis/csc/CaffeineCSC.java
  src/main/java/redis/clients/jedis/csc/ClientSideCache.java
  src/main/java/redis/clients/jedis/csc/GuavaCSC.java
  src/main/java/redis/clients/jedis/csc/hash/AbstractCommandHashing.java
  src/main/java/redis/clients/jedis/csc/hash/CommandLongHashing.java
  src/main/java/redis/clients/jedis/csc/hash/GuavaHashing.java
  src/main/java/redis/clients/jedis/csc/hash/OpenHftHashing.java
  src/main/java/redis/clients/jedis/csc/hash/PrimitiveArrayHashing.java
  src/main/java/redis/clients/jedis/util/JedisURIHelper.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheLibsTest.java
  src/test/java/redis/clients/jedis/csc/MapCSC.java
Labels: experimental

#3759 Add unit tests for pipelining - migrate and db commands
  src/test/java/redis/clients/jedis/MigratePipeliningTest.java
  src/test/java/redis/clients/jedis/PipeliningTest.java
Labels: testing

#3288 Add Hashes pipeline commands unit tests
  src/test/java/redis/clients/jedis/commands/unified/pipeline/HashesPipelineCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pipeline/PipelineCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledCommandsTestHelper.java
  src/test/java/redis/clients/jedis/util/AssertUtil.java
Labels: testing

#3758 Client-side cache related naming changes
  src/main/java/redis/clients/jedis/csc/CaffeineClientSideCache.java
  src/main/java/redis/clients/jedis/csc/ClientSideCache.java
  src/main/java/redis/clients/jedis/csc/GuavaClientSideCache.java
  src/main/java/redis/clients/jedis/csc/hash/AbstractCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/CommandLongHasher.java
  src/main/java/redis/clients/jedis/csc/hash/CommandLongHashing.java
  src/main/java/redis/clients/jedis/csc/hash/GuavaCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/OpenHftCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/PrimitiveArrayCommandHasher.java
  src/main/java/redis/clients/jedis/util/JedisURIHelper.java
  src/test/java/redis/clients/jedis/csc/AllowAndDenyListClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheLibsTest.java
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisPooledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/MapClientSideCache.java
Labels: experimental

#3761 Reformat clientSideCache variable names
  src/main/java/redis/clients/jedis/Connection.java
  src/main/java/redis/clients/jedis/ConnectionFactory.java
  src/main/java/redis/clients/jedis/ConnectionPool.java
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/JedisPooled.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java
  src/main/java/redis/clients/jedis/providers/PooledConnectionProvider.java
Labels: experimental

#3751 Add support for redis command: CLIENT TRACKINGINFO
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/commands/ClientCommands.java
  src/main/java/redis/clients/jedis/resps/TrackingInfo.java
  src/test/java/redis/clients/jedis/commands/jedis/ClientCommandsTest.java
Labels: feature

#3763 Add tests for Stream pipelined commands
  src/test/java/redis/clients/jedis/MigratePipeliningTest.java
  src/test/java/redis/clients/jedis/commands/unified/pipeline/StreamsPipelineCommandsTest.java
Labels: testing

#3768 GETSET command is deprecated since Redis 6.2.0
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipeliningBase.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StringBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/StringPipelineCommands.java
Labels: maintenance

#3764 Reenable clustering tests
  Makefile
  src/test/java/redis/clients/jedis/HostAndPorts.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterAllKindOfValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterBinaryValuesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterBitCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterCommandsTestHelper.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterGeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterHyperLogLogCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterSortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterStringValuesCommandsTest.java
Labels: testing

#3767 Geo pipelined tests
  src/test/java/redis/clients/jedis/commands/unified/pipeline/GeoPipelineCommandsTest.java
  src/test/java/redis/clients/jedis/util/GeoCoordinateMatcher.java
Labels: testing

#3771 Add pipelined tests for sorted sets
  src/test/java/redis/clients/jedis/commands/unified/pipeline/SortedSetPipelineCommandsTest.java
Labels: testing

#3773 Fix typo in SetPipelineCommands method name
  src/main/java/redis/clients/jedis/PipeliningBase.java
  src/main/java/redis/clients/jedis/commands/SetPipelineCommands.java
  src/test/java/redis/clients/jedis/ClusterPipeliningTest.java
Labels: maintenance

#3777 Use expiryOption in PipelineBase.expireAt
  src/main/java/redis/clients/jedis/PipeliningBase.java
Labels: backport required, bug

#3778 Extensive unit tests for PipeliningBase
  src/test/java/redis/clients/jedis/PipeliningBaseTest.java
  src/test/java/redis/clients/jedis/commands/jedis/SlowlogCommandsTest.java
Labels: testing

#3772 Pipelined tests for lists and sets, and API typo fix
  src/test/java/redis/clients/jedis/commands/unified/pipeline/ListPipelineCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pipeline/SetPipelineCommandsTest.java
Labels: testing

#3782 Fix UnifiedJedis pexpireAt glitch
  src/main/java/redis/clients/jedis/UnifiedJedis.java
Labels: backport required, bug

#3784 Fix ZREVRANGE versions with max/min swapped in MultiNodePipelineBase
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
Labels: bug

#3728 SetParams should implement equals and hashcode issue #2687
  src/main/java/redis/clients/jedis/args/RawableFactory.java
  src/main/java/redis/clients/jedis/params/BitPosParams.java
  src/main/java/redis/clients/jedis/params/ClientKillParams.java
  src/main/java/redis/clients/jedis/params/CommandListFilterByParams.java
  src/main/java/redis/clients/jedis/params/FailoverParams.java
  src/main/java/redis/clients/jedis/params/GeoAddParams.java
  src/main/java/redis/clients/jedis/params/GetExParams.java
  src/main/java/redis/clients/jedis/params/LCSParams.java
  src/main/java/redis/clients/jedis/params/LPosParams.java
  src/main/java/redis/clients/jedis/params/LolwutParams.java
  src/main/java/redis/clients/jedis/params/MigrateParams.java
  src/main/java/redis/clients/jedis/params/ModuleLoadExParams.java
  src/main/java/redis/clients/jedis/params/RestoreParams.java
  src/main/java/redis/clients/jedis/params/ScanParams.java
  src/main/java/redis/clients/jedis/params/SetParams.java
  src/main/java/redis/clients/jedis/params/ShutdownParams.java
  src/main/java/redis/clients/jedis/params/SortingParams.java
  src/main/java/redis/clients/jedis/params/XAddParams.java
  src/main/java/redis/clients/jedis/params/XAutoClaimParams.java
  src/main/java/redis/clients/jedis/params/XClaimParams.java
  src/main/java/redis/clients/jedis/params/XPendingParams.java
  src/main/java/redis/clients/jedis/params/XReadGroupParams.java
  src/main/java/redis/clients/jedis/params/XReadParams.java
  src/main/java/redis/clients/jedis/params/XTrimParams.java
  src/main/java/redis/clients/jedis/params/ZAddParams.java
  src/main/java/redis/clients/jedis/params/ZIncrByParams.java
  src/main/java/redis/clients/jedis/params/ZParams.java
  src/main/java/redis/clients/jedis/params/ZRangeParams.java
  src/test/java/redis/clients/jedis/params/BitPosParamsTest.java
  src/test/java/redis/clients/jedis/params/ClientKillParamsTest.java
  src/test/java/redis/clients/jedis/params/CommandListFilterByParamsTest.java
  src/test/java/redis/clients/jedis/params/FailoverParamsTest.java
  src/test/java/redis/clients/jedis/params/GeoAddParamsTest.java
  src/test/java/redis/clients/jedis/params/GetExParamsTest.java
  src/test/java/redis/clients/jedis/params/LCSParamsTest.java
  src/test/java/redis/clients/jedis/params/LPosParamsTest.java
  src/test/java/redis/clients/jedis/params/LolwutParamsTest.java
  src/test/java/redis/clients/jedis/params/MigrateParamsTest.java
  src/test/java/redis/clients/jedis/params/ModuleLoadExParamsTest.java
  src/test/java/redis/clients/jedis/params/RestoreParamsTest.java
  src/test/java/redis/clients/jedis/params/ScanParamsTest.java
  src/test/java/redis/clients/jedis/params/SetParamsTest.java
  src/test/java/redis/clients/jedis/params/ShutdownParamsTest.java
  src/test/java/redis/clients/jedis/params/SortingParamsTest.java
  src/test/java/redis/clients/jedis/params/XAddParamsTest.java
  src/test/java/redis/clients/jedis/params/XAutoClaimParamsTest.java
  src/test/java/redis/clients/jedis/params/XClaimParamsTest.java
  src/test/java/redis/clients/jedis/params/XPendingParamsTest.java
  src/test/java/redis/clients/jedis/params/XReadGroupParamsTest.java
  src/test/java/redis/clients/jedis/params/XReadParamsTest.java
  src/test/java/redis/clients/jedis/params/XTrimParamsTest.java
  src/test/java/redis/clients/jedis/params/ZAddParamsTest.java
  src/test/java/redis/clients/jedis/params/ZIncrByParamsTest.java
  src/test/java/redis/clients/jedis/params/ZParamsTest.java
  src/test/java/redis/clients/jedis/params/ZRangeParamsTest.java
Labels: enhancement

#3787 Align Pipelined commands with UnifiedJedis
  src/main/java/redis/clients/jedis/PipeliningBase.java
  src/main/java/redis/clients/jedis/bloom/commands/CuckooFilterPipelineCommands.java
  src/main/java/redis/clients/jedis/timeseries/RedisTimeSeriesPipelineCommands.java
Labels: maintenance

#3790 Add Experimental, Internal and VisibleForTesting annotations
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/annots/Experimental.java
  src/main/java/redis/clients/jedis/annots/Internal.java
  src/main/java/redis/clients/jedis/annots/VisibleForTesting.java
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
  src/main/java/redis/clients/jedis/executors/RetryableCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverBase.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverConnectionProvider.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterPipeline.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterTransaction.java
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
Labels: feature

#3791 Add last entry id for XREADs and support XREADs reply as map
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipeliningBase.java
  src/main/java/redis/clients/jedis/StreamEntryID.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/StreamCommands.java
  src/main/java/redis/clients/jedis/commands/StreamPipelineCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pipeline/StreamsPipelineCommandsTest.java
  src/test/java/redis/clients/jedis/params/XPendingParamsTest.java
Labels: enhancement

#3793 Consider null values in empty StreamPendingSummary
  src/main/java/redis/clients/jedis/BuilderFactory.java
  src/test/java/redis/clients/jedis/commands/jedis/StreamsCommandsTest.java
Labels: backport required, bug
