Repository redis/jedis, pull requests merged in 2024-04, with the labels that each got.

#3788 Add extensive tests for UnifiedJedis
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/test/java/redis/clients/jedis/PipeliningBaseTest.java
  src/test/java/redis/clients/jedis/UnifiedJedisCustomCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/MockedCommandObjectsTestBase.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseBitmapCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseBloomFilterCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseCountMinSketchCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseCuckooFilterCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseGenericCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseGeospatialCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseGraphCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseHashCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseHyperloglogCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseJsonCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseListCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseMiscellaneousTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseMockedTestBase.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseScriptingAndFunctionsCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseSearchAndQueryCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseServerManagementCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseSetCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseSortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseStreamCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseStringCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseTDigestCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseTimeSeriesCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseTopKCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisBitmapCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisBloomFilterCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisConnectionManagementCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisCountMinSketchCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisCuckooFilterCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisGenericCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisGeospatialCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisHashCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisHyperloglogCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisJsonCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisListCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisMockedTestBase.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisPubSubCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisScriptingAndFunctionsCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisSearchAndQueryCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisServerManagementCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisSetCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisSortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisStreamCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisStringCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisTDigestCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisTimeSeriesCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisTopKCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisTriggersAndFunctionsCommandsTest.java
Labels: testing, maintenance

#3796 Extensive unit tests for the CommandObjects class
  pom.xml
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsBitmapCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsBloomFilterCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsCountMinSketchCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsCuckooFilterCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsGenericCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsGeospatialCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsHashCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsHyperloglogCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsJsonCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsModulesTestBase.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsScriptingCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsSearchAndQueryCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsServerManagementCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsSortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsStandaloneTestBase.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsStreamCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsStringCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsTDigestCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsTestBase.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsTimeSeriesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsTopkCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsTriggersAndFunctionsCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/Person.java
Labels: testing

#3799 Fix client side cache tests
  src/test/java/redis/clients/jedis/csc/JedisClusterClientSideCacheTest.java
  src/test/java/redis/clients/jedis/csc/JedisSentineledClientSideCacheTest.java
Labels: testing, experimental

#3800 Remove openhft hashing from source dependency
  pom.xml
  src/main/java/redis/clients/jedis/csc/CaffeineClientSideCache.java
  src/main/java/redis/clients/jedis/csc/hash/AbstractSimpleCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/GuavaCommandHasher.java
  src/main/java/redis/clients/jedis/csc/hash/SimpleCommandHasher.java
  src/test/java/redis/clients/jedis/csc/ClientSideCacheLibsTest.java
  src/test/java/redis/clients/jedis/csc/MapClientSideCache.java
  src/test/java/redis/clients/jedis/csc/OpenHftCommandHasher.java
Labels: experimental

#3804 Support transaction from UnifiedJedis without calling multi first
  src/main/java/redis/clients/jedis/JedisCluster.java
  src/main/java/redis/clients/jedis/JedisSharding.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/test/java/redis/clients/jedis/commands/unified/pooled/PooledMiscellaneousTest.java
Labels: enhancement, breakingchange

#3810 Resolve compile warnings
  src/test/java/redis/clients/jedis/UnifiedJedisCustomCommandsTest.java
Labels: testing

#3809 Add more tests for the CommandObjects class
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsGenericCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsSearchAndQueryCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsSortedSetCommandsTest.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsStreamCommandsTest.java
Labels: testing

#3801 Custom connection pool to MultiClusterPooledConnectionProvider
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
  src/test/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProviderTest.java
Labels: backport required, enhancement

#3827 Modify and fail-fast GeoSearchParam
  src/main/java/redis/clients/jedis/params/GeoSearchParam.java
  src/test/java/redis/clients/jedis/commands/jedis/GeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/GeoCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/cluster/ClusterGeoCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/pipeline/GeoPipelineCommandsTest.java
Labels: testing, breakingchange, maintenance
