Repository redis/jedis, pull requests merged in 2025-01, with the labels that each got.

#4050 DOC-4450 added hgetall and hvals command examples
  src/test/java/io/redis/examples/CmdsHashExample.java
Labels: docs-review

#4051 Remove List tests asserting timeouts
  src/test/java/redis/clients/jedis/commands/jedis/ListCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/ListCommandsTestBase.java
  src/test/java/redis/clients/jedis/commands/unified/pipeline/ListPipelineCommandsTest.java
Labels: testing

#4053 Fix sporadic test failing with OOM
  .github/workflows/test-on-docker.yml
  pom.xml
  src/test/java/redis/clients/jedis/authentication/TokenBasedAuthenticationUnitTests.java
Labels: testing

#4052 DOC-4495 sadd and smembers examples
  src/test/java/io/redis/examples/CmdsSetExample.java
Labels: docs-review

#4054 DOC-4475 examples for llen, lpop, lpush, lrange, rpop, and rpush
  src/test/java/io/redis/examples/CmdsListExample.java
Labels: docs-review

#4061 Use v4 of upload artifact
  .github/workflows/test-on-docker.yml
Labels: testing

#4062 Upgrade GitHub Python artifact for Publish Docs
  .github/workflows/docs.yml
Labels: maintenance

#4063 Use v3 of GitHub upload-pages-artifact for Publish Docs
  .github/workflows/docs.yml
Labels: maintenance

#4064 Use v3 of GitHub deploy-pages for Publish Docs
  .github/workflows/docs.yml
Labels: maintenance

#4065 Revert failing GitHub artifacts for Publish Docs
  .github/workflows/docs.yml
Labels: maintenance

#4058 DOC-4440 added auth command examples using Jedis class
  src/test/java/io/redis/examples/CmdsCnxmgmtExample.java
Labels: docs-review

#4059 DOC-4732 added geo index examples
  src/test/java/io/redis/examples/GeoIndexExample.java
Labels: docs-review

#4066 Update actions/checkout, actions/setup-java and codecov/codecov-action
  .github/workflows/test-on-docker.yml
Labels: maintenance

#4056 DOC-4445 server management command examples
  src/test/java/io/redis/examples/CmdsServerMgmtExample.java
Labels: docs-review

#4069 Test with 8.0-M04-pre
  .github/workflows/test-on-docker.yml
  Makefile
  src/test/java/redis/clients/jedis/modules/search/AggregationTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchDefaultDialectTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/util/RedisConditions.java
Labels: testing

#4042 Test modules ACL support
  src/test/java/redis/clients/jedis/commands/jedis/JedisCommandsTestBase.java
  src/test/java/redis/clients/jedis/modules/ConsolidatedAccessControlListCommandsTest.java
  src/test/java/redis/clients/jedis/modules/RedisModuleCommandsTestBase.java
Labels: maintenance

#4072 Remove SearchConfigTest
  src/test/java/redis/clients/jedis/modules/search/SearchConfigTest.java
Labels: testing

#3958 Support warning messages in search/aggregation query results
  src/main/java/redis/clients/jedis/search/SearchResult.java
  src/main/java/redis/clients/jedis/search/aggr/AggregationResult.java
  src/test/java/redis/clients/jedis/modules/ConsolidatedConfigurationCommandsTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchDefaultDialectTest.java
Labels: experimental

#3969 Remove Triggers and Functions feature
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/RedisModuleCommands.java
  src/main/java/redis/clients/jedis/gears/RedisGearsCommands.java
  src/main/java/redis/clients/jedis/gears/RedisGearsProtocol.java
  src/main/java/redis/clients/jedis/gears/TFunctionListParams.java
  src/main/java/redis/clients/jedis/gears/TFunctionLoadParams.java
  src/main/java/redis/clients/jedis/gears/resps/FunctionInfo.java
  src/main/java/redis/clients/jedis/gears/resps/FunctionStreamInfo.java
  src/main/java/redis/clients/jedis/gears/resps/GearsLibraryInfo.java
  src/main/java/redis/clients/jedis/gears/resps/StreamTriggerInfo.java
  src/main/java/redis/clients/jedis/gears/resps/TriggerInfo.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsTriggersAndFunctionsCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/MockedCommandObjectsTestBase.java
  src/test/java/redis/clients/jedis/mocked/unified/UnifiedJedisTriggersAndFunctionsCommandsTest.java
  src/test/java/redis/clients/jedis/modules/gears/GearsTest.java
Labels: breakingchange

#4073 Remove Graph module support
  src/main/java/redis/clients/jedis/ClusterPipeline.java
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/MultiNodePipelineBase.java
  src/main/java/redis/clients/jedis/Pipeline.java
  src/main/java/redis/clients/jedis/PipeliningBase.java
  src/main/java/redis/clients/jedis/ReliableTransaction.java
  src/main/java/redis/clients/jedis/ShardedPipeline.java
  src/main/java/redis/clients/jedis/Transaction.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/RedisModuleCommands.java
  src/main/java/redis/clients/jedis/commands/RedisModulePipelineCommands.java
  src/main/java/redis/clients/jedis/graph/GraphCache.java
  src/main/java/redis/clients/jedis/graph/GraphCommandObjects.java
  src/main/java/redis/clients/jedis/graph/GraphProtocol.java
  src/main/java/redis/clients/jedis/graph/GraphQueryParams.java
  src/main/java/redis/clients/jedis/graph/Header.java
  src/main/java/redis/clients/jedis/graph/Record.java
  src/main/java/redis/clients/jedis/graph/RedisGraphCommands.java
  src/main/java/redis/clients/jedis/graph/RedisGraphPipelineCommands.java
  src/main/java/redis/clients/jedis/graph/RedisGraphQueryUtil.java
  src/main/java/redis/clients/jedis/graph/ResultSet.java
  src/main/java/redis/clients/jedis/graph/ResultSetBuilder.java
  src/main/java/redis/clients/jedis/graph/Statistics.java
  src/main/java/redis/clients/jedis/graph/entities/Edge.java
  src/main/java/redis/clients/jedis/graph/entities/GraphEntity.java
  src/main/java/redis/clients/jedis/graph/entities/Node.java
  src/main/java/redis/clients/jedis/graph/entities/Path.java
  src/main/java/redis/clients/jedis/graph/entities/Point.java
  src/main/java/redis/clients/jedis/graph/entities/Property.java
  src/main/java/redis/clients/jedis/graph/entities/package-info.java
  src/main/java/redis/clients/jedis/graph/package-info.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterPipeline.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterTransaction.java
  src/test/java/redis/clients/jedis/mocked/MockedCommandObjectsTestBase.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseGraphCommandsTest.java
  src/test/java/redis/clients/jedis/mocked/pipeline/PipeliningBaseMockedTestBase.java
  src/test/java/redis/clients/jedis/modules/graph/GraphAPITest.java
  src/test/java/redis/clients/jedis/modules/graph/GraphPipelineTest.java
  src/test/java/redis/clients/jedis/modules/graph/GraphTransactionTest.java
  src/test/java/redis/clients/jedis/modules/graph/GraphValuesTest.java
  src/test/java/redis/clients/jedis/modules/graph/PathBuilder.java
  src/test/java/redis/clients/jedis/modules/graph/PathBuilderTest.java
  src/test/java/redis/clients/jedis/modules/graph/PathTest.java
  src/test/java/redis/clients/jedis/modules/graph/UtilsTest.java
Labels: breakingchange

#4075 Use v4 of few GitHub actions workflow artifacts
  .github/workflows/codeql-analysis.yml
  .github/workflows/doctests.yml
  .github/workflows/integration.yml
  .github/workflows/snapshot.yml
  .github/workflows/spellcheck.yml
  .github/workflows/version-and-release.yml
Labels: maintenance

#4074 Fix the Java example code for Lists using RPUSH
  src/test/java/io/redis/examples/ListExample.java
Labels: docs-review
