Repository redis/jedis, pull requests merged in 2025-04, with the labels that each got.

#4125 Document pgp keys
  .github/wordlist.txt
  docs/verifying-artifacts.md
  mkdocs.yml
Labels: maintenance

#4133 Update verifying content doc
  docs/verifying-artifacts.md
Labels: documentation, skip-changelog, churn

#4131 Fix failing ModuleTest & test against 8.0-RC1-pre
  src/test/java/redis/clients/jedis/commands/jedis/ModuleTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
  src/test/resources/env/.env
Labels: testing, maintenance, skip-changelog

#4134 Update "Pipelines and transactions" doc example to include pipeline.close()
  src/test/java/io/redis/examples/PipeTransExample.java
Labels: documentation, skip-changelog, docs-review

#4138 Fix flaky test JedisPoolTest.testCloseConnectionOnMakeObject
  src/test/java/redis/clients/jedis/ACLJedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPoolTest.java
Labels: testing, maintenance, skip-changelog

#4142 Fix for connectionAuthWithExpiredTokenTest
  src/test/java/redis/clients/jedis/authentication/RedisEntraIDIntegrationTests.java
Labels: maintenance
