Repository redis/jedis, pull requests merged in 2025-09, with the labels that each got.

#4270 [automatic failover] Remove the check for 'GenericObjectPool.getNumWaiters()' in 'TrackingConnectionPool'
  src/main/java/redis/clients/jedis/mcf/TrackingConnectionPool.java
Labels: feature

#4284 Add a fresh coat of paint to the README
  README.md
Labels: maintenance, skip-changelog

#4285 Fix #4147: Broken links at https://redis.github.io/jedis/
  README.md
  mkdocs.yml
Labels: documentation
