Repository redis/jedis, pull requests merged in 2025-10, with the labels that each got.

#4295 [automatic failover] Add dual thresholds (min num of failures + failure rate) capabililty to circuit breaker
  docs/failover.md
  pom.xml
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverBase.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverConnectionProvider.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerThresholdsAdapter.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterPooledConnectionProvider.java
  src/test/java/redis/clients/jedis/failover/FailoverIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/ActiveActiveLocalFailoverTest.java
  src/test/java/redis/clients/jedis/mcf/CircuitBreakerThresholdsTest.java
  src/test/java/redis/clients/jedis/mcf/ClusterEvaluateThresholdsTest.java
  src/test/java/redis/clients/jedis/mcf/FailbackMechanismUnitTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckTest.java
  src/test/java/redis/clients/jedis/mcf/MultiClusterFailoverAttemptsConfigTest.java
  src/test/java/redis/clients/jedis/mcf/MultiClusterPooledConnectionProviderTest.java
  src/test/java/redis/clients/jedis/mcf/StatusTrackerTest.java
  src/test/java/redis/clients/jedis/misc/AutomaticFailoverTest.java
  src/test/java/redis/clients/jedis/scenario/ActiveActiveFailoverTest.java
  src/test/java/redis/clients/jedis/util/ReflectionTestUtil.java
Labels: breakingchange, feature

#4306 [automatic failover] Automatic failover client improvements (part 3)
  docs/failover.md
  pom.xml
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/MultiDbClient.java
  src/main/java/redis/clients/jedis/builders/MultiDbClientBuilder.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverBase.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverConnectionProvider.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerThresholdsAdapter.java
  src/main/java/redis/clients/jedis/mcf/ClusterSwitchEventArgs.java
  src/main/java/redis/clients/jedis/mcf/EchoStrategy.java
  src/main/java/redis/clients/jedis/mcf/HealthCheckStrategy.java
  src/main/java/redis/clients/jedis/mcf/LagAwareStrategy.java
  src/main/java/redis/clients/jedis/mcf/MultiClusterPooledConnectionProvider.java
  src/test/java/redis/clients/jedis/MultiDbClientTest.java
  src/test/java/redis/clients/jedis/failover/FailoverIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/ActiveActiveLocalFailoverTest.java
  src/test/java/redis/clients/jedis/mcf/CircuitBreakerThresholdsTest.java
  src/test/java/redis/clients/jedis/mcf/ClusterEvaluateThresholdsTest.java
  src/test/java/redis/clients/jedis/mcf/DefaultValuesTest.java
  src/test/java/redis/clients/jedis/mcf/FailbackMechanismUnitTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckTest.java
  src/test/java/redis/clients/jedis/mcf/LagAwareStrategyUnitTest.java
  src/test/java/redis/clients/jedis/mcf/MultiClusterFailoverAttemptsConfigTest.java
  src/test/java/redis/clients/jedis/mcf/MultiClusterPooledConnectionProviderTest.java
  src/test/java/redis/clients/jedis/mcf/StatusTrackerTest.java
  src/test/java/redis/clients/jedis/misc/AutomaticFailoverTest.java
  src/test/java/redis/clients/jedis/scenario/ActiveActiveFailoverTest.java
  src/test/java/redis/clients/jedis/util/ClientTestUtil.java
  src/test/java/redis/clients/jedis/util/ReflectionTestUtil.java
Labels: feature

#4310 [automatic failover] Refactor MultiDb API: Rename endpoint methods to database and encapsulate retry/circuit breaker configuration
  docs/failover.md
  src/main/java/redis/clients/jedis/MultiDbClient.java
  src/main/java/redis/clients/jedis/MultiDbConfig.java
  src/main/java/redis/clients/jedis/builders/MultiDbClientBuilder.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerThresholdsAdapter.java
  src/main/java/redis/clients/jedis/mcf/JedisFailoverException.java
  src/main/java/redis/clients/jedis/mcf/MultiDbCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/MultiDbConnectionProvider.java
  src/main/java/redis/clients/jedis/mcf/MultiDbConnectionSupplier.java
  src/main/java/redis/clients/jedis/mcf/MultiDbFailoverBase.java
  src/test/java/redis/clients/jedis/MultiDbClientTest.java
  src/test/java/redis/clients/jedis/failover/FailoverIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/ActiveActiveLocalFailoverTest.java
  src/test/java/redis/clients/jedis/mcf/DatabaseEvaluateThresholdsTest.java
  src/test/java/redis/clients/jedis/mcf/DefaultValuesTest.java
  src/test/java/redis/clients/jedis/mcf/FailbackMechanismIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/FailbackMechanismUnitTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckTest.java
  src/test/java/redis/clients/jedis/mcf/MultiDbCircuitBreakerThresholdsTest.java
  src/test/java/redis/clients/jedis/mcf/MultiDbConnectionProviderDynamicEndpointUnitTest.java
  src/test/java/redis/clients/jedis/mcf/MultiDbConnectionProviderFailoverAttemptsConfigTest.java
  src/test/java/redis/clients/jedis/mcf/MultiDbConnectionProviderHelper.java
  src/test/java/redis/clients/jedis/mcf/MultiDbConnectionProviderInitializationTest.java
  src/test/java/redis/clients/jedis/mcf/MultiDbConnectionProviderTest.java
  src/test/java/redis/clients/jedis/mcf/PeriodicFailbackTest.java
  src/test/java/redis/clients/jedis/misc/AutomaticFailoverTest.java
  src/test/java/redis/clients/jedis/providers/MultiDbProviderHealthStatusChangeTest.java
  src/test/java/redis/clients/jedis/scenario/ActiveActiveFailoverTest.java
Labels: breakingchange
