Repository redis/jedis, pull requests merged in 2025-03, with the labels that each got.

#4105 [Backport][5.2.1] Extend EXECABORT with "previous errors" #4084
  src/main/java/redis/clients/jedis/Transaction.java
  src/test/java/redis/clients/jedis/TransactionV2Test.java
Labels: enhancement

#4104 [Backport][5.2.1] Propagate cause for "Cluster retry deadline exceeded" exception #4103
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
Labels: enhancement

#4101 Update stale issue workflow
  .github/workflows/stale-issues.yml
Labels: maintenance

#4109 Fix for bug #4003. Better message instead of ArrayIndexOutOfBoundsExce
  src/main/java/redis/clients/jedis/util/JedisURIHelper.java
  src/test/java/redis/clients/jedis/util/JedisURIHelperTest.java
Labels: bug

#4113 Test support for DefaultAzureCredential
  pom.xml
  src/test/java/redis/clients/jedis/authentication/RedisEntraIDIntegrationTests.java
Labels: testing

#4095 Support for new HFE API, hgetdel hgetex hsetex commands
  .github/wordlist.txt
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/Jedis.java
  src/main/java/redis/clients/jedis/PipeliningBase.java
  src/main/java/redis/clients/jedis/Protocol.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/commands/HashBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/HashCommands.java
  src/main/java/redis/clients/jedis/commands/HashPipelineBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/HashPipelineCommands.java
  src/main/java/redis/clients/jedis/params/BaseGetExParams.java
  src/main/java/redis/clients/jedis/params/BaseSetExParams.java
  src/main/java/redis/clients/jedis/params/GetExParams.java
  src/main/java/redis/clients/jedis/params/HGetExParams.java
  src/main/java/redis/clients/jedis/params/HSetExParams.java
  src/main/java/redis/clients/jedis/params/SetParams.java
  src/test/java/redis/clients/jedis/commands/commandobjects/CommandObjectsHashCommandsTest.java
  src/test/java/redis/clients/jedis/commands/jedis/HashesCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/HashesCommandsTestBase.java
Labels: feature

#4118 Fix failing network partition test
  src/test/java/redis/clients/jedis/authentication/RedisEntraIDIntegrationTests.java
Labels: testing

#4076 Link Jedis 5 migration guide in mkdocs
  mkdocs.yml
Labels: skip-changelog, docs-review
