Repository redis/jedis, pull requests merged in 2025-07, with the labels that each got.

#4190 Add Support for New BITOP Operations in Redis 8.2 (#4188)
  src/main/java/redis/clients/jedis/args/BitOP.java
  src/main/java/redis/clients/jedis/commands/BitBinaryCommands.java
  src/main/java/redis/clients/jedis/commands/BitCommands.java
  src/test/java/redis/clients/jedis/commands/jedis/BitCommandsTest.java
  src/test/java/redis/clients/jedis/commands/unified/BitCommandsTestBase.java
Labels: feature

#4206 Fix flaky test ClientCommandsTest.killSkipmeYesNo
  src/test/java/redis/clients/jedis/commands/jedis/ClientCommandsTest.java
Labels: maintenance

#4205 Fix memory leak in JedisClusterInfoCache - replica nodes not cleared
  src/main/java/redis/clients/jedis/JedisClusterInfoCache.java
  src/test/java/redis/clients/jedis/JedisClusterInfoCacheTest.java
  src/test/java/redis/clients/jedis/util/CommandArgumentMatchers.java
Labels: bug

#4212 Check formatting only for new files
  .github/workflows/format_check.yml
Labels: maintenance, skip-changelog, churn
