Repository redis/jedis, pull requests merged in 2025-08, with the labels that each got.

#4222 Add support for SVS-VAMANA vector indexing
  src/main/java/redis/clients/jedis/search/Schema.java
  src/main/java/redis/clients/jedis/search/schemafields/VectorField.java
  src/test/java/redis/clients/jedis/modules/search/SchemaTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: feature

#4225 Restore binary compatibility of SetParams
  src/main/java/redis/clients/jedis/params/BaseSetExParams.java
  src/main/java/redis/clients/jedis/params/SetParams.java
Labels: backport required, bug

#4189 [automatic failover] Implement HealtStatusManager + weighted endpoints
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/main/java/redis/clients/jedis/HostAndPort.java
  src/main/java/redis/clients/jedis/MultiClusterClientConfig.java
  src/main/java/redis/clients/jedis/UnifiedJedis.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerCommandExecutor.java
  src/main/java/redis/clients/jedis/mcf/CircuitBreakerFailoverBase.java
  src/main/java/redis/clients/jedis/mcf/EchoStrategy.java
  src/main/java/redis/clients/jedis/mcf/Endpoint.java
  src/main/java/redis/clients/jedis/mcf/FailoverOptions.java
  src/main/java/redis/clients/jedis/mcf/HealthCheck.java
  src/main/java/redis/clients/jedis/mcf/HealthCheckCollection.java
  src/main/java/redis/clients/jedis/mcf/HealthCheckStrategy.java
  src/main/java/redis/clients/jedis/mcf/HealthStatus.java
  src/main/java/redis/clients/jedis/mcf/HealthStatusChangeEvent.java
  src/main/java/redis/clients/jedis/mcf/HealthStatusListener.java
  src/main/java/redis/clients/jedis/mcf/HealthStatusManager.java
  src/main/java/redis/clients/jedis/mcf/LagAwareStrategy.java
  src/main/java/redis/clients/jedis/mcf/RedisRestAPIHelper.java
  src/main/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProvider.java
  src/test/java/redis/clients/jedis/failover/FailoverIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckIntegrationTest.java
  src/test/java/redis/clients/jedis/mcf/HealthCheckTest.java
  src/test/java/redis/clients/jedis/misc/AutomaticFailoverTest.java
  src/test/java/redis/clients/jedis/providers/MultiClusterPooledConnectionProviderTest.java
  src/test/java/redis/clients/jedis/scenario/ActiveActiveFailoverTest.java
Labels: feature

#4232 Bump test infra to Redis 8.2 GA
  Makefile
  src/test/resources/env/.env
Labels: maintenance, skip-changelog

#4227 docs: Improve Javadoc for HostAndPortMapper (#4112)
  .github/wordlist.txt
  docs/advanced-usage.md
  src/main/java/redis/clients/jedis/HostAndPortMapper.java
Labels: documentation

#4236 [automatic failover] Replace 'SimpleEntry' with 'HealthCheckResult'
  src/main/java/redis/clients/jedis/mcf/HealthCheck.java
Labels: feature
