Repository redis/jedis, pull requests merged in 2025-02, with the labels that each got.

#4086 Fix pubsub when cache enabled
  src/main/java/redis/clients/jedis/Protocol.java
  src/test/java/redis/clients/jedis/csc/UnifiedJedisClientSideCacheTestBase.java
Labels: bug

#4060 Make default client side search dialect to 2
  src/main/java/redis/clients/jedis/CommandObjects.java
  src/test/java/redis/clients/jedis/modules/search/JsonSearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchTest.java
  src/test/java/redis/clients/jedis/modules/search/SearchWithParamsTest.java
Labels: breakingchange

#4090 Extend EXECABORT with "previous errors" #4084
  src/main/java/redis/clients/jedis/Transaction.java
  src/test/java/redis/clients/jedis/TransactionV2Test.java
Labels: enhancement

#4087 Enforce code style format
  .github/workflows/format_check.yml
  formatter-pom.xml
  hbase-formatter.xml
  pom.xml
  src/main/java/redis/clients/jedis/annots/Experimental.java
  src/main/java/redis/clients/jedis/annots/Internal.java
  src/main/java/redis/clients/jedis/annots/VisibleForTesting.java
Labels: maintenance

#4102 Basic documention for TBA support with some examples
  .github/wordlist.txt
  README.md
  docs/advanced-usage.md
Labels: documentation

#4103 Propagate cause for "Cluster retry deadline exceeded" exception
  src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java
Labels: enhancement
