Repository redis/jedis, pull requests merged in 2025-06, with the labels that each got.

#4179 Update test infra to use latest Redis
  Makefile
  src/test/java/redis/clients/jedis/ACLJedisPoolTest.java
  src/test/java/redis/clients/jedis/JedisPoolTest.java
  src/test/resources/env/.env
  src/test/resources/env/.env.v7.2
  src/test/resources/env/.env.v7.4
Labels: maintenance, churn

#4182 Add a test to verify failover on DNS unresolvable host error
  src/test/java/redis/clients/jedis/misc/AutomaticFailoverTest.java
Labels: testing, skip-changelog

#4184 DOC-5227 added probabilistic data type examples
  src/test/java/io/redis/examples/HomeProbDtsExample.java
Labels: documentation
